[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]I rarely come book shopping[n]like this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do wonder what I should get...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Do you not read?[e]
[s]What is your favorite genre?[e]
[s]It's all the same to me.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8161 65535 0]I do. I just do not have time.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There is barely any time in between[n]my public image and the metaverse.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]I suppose mystery would be[n]my favorite.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 4191 65535 0]Then why did you bring me here?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In the end, I do not exactly read[n]much due to time constraints.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I suppose I should get something[n]to read as I wait for us to[n]go into Maruki's palace...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]I shall get something which[n]will be of use, then.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 8 2 0 8020 65535 0]Having something like this will[n]be useful to me. It was worthwhile[n]to come here.[n][f 1 3 65535][w][e]

