[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]I have come here once or[n]twice before. It is a surprisingly[n]quiet area.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]For what reason would there[n]be to come here, [fName]?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It does not seem productive[n]in any way to be here.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]To make a wish.[e]
[s]To pray.[e]
[s]Figured you'd like it.[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]A wish?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If you need something, praying[n]to a god will get you no where.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]After what you've dealt with,[n]you still want to pray to gods?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you asking for more trouble?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]You... thought I'd what?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do guess this is a peaceful area.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Harajuku is next to us, but there[n]is no sound interrupting this place.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I suppose a shrine would be[n]good for focusing if you[n]truly had no where else to go.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Speaking of which, have you[n]been focusing on the mission?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do hope you are not using me[n]as a distraction from your job.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]We need to do this. We need[n]to take Maruki down. Remember that.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If this pretend is causing issues,[n]I will stop with no hesitation.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]It is time to go. Goodbye.[n][f 1 3 65535][w][e]

