[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]I am rather excited for this event.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Looking up at the expansive universe,[n]lover by your side...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Truly, a romantic option to have chosen...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah. It is starting.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The vibrant colors, the blazing stars[n]among the cosmos...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The passion! It is truly emmaculate![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]We're in public...[e]
[s][f 0 8 2 1 2217]You're energetic.[clr 27][e]
[s]Yusuke...[e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0][coop 5 5 5]What does that have to do with[n]the infinite possibilities in[n]front of our eyes!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Can you feel it, [fName]?[n]The swarming romance of the situation?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Truly, this is something to paint![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0][coop 5 10 5]How could I not be in such a situation!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The romance of the cosmos is[n]something I must put to a canvas![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 5 5 5]What? Do you see as well?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]The way the darkness of space brings[n]a blinding burst of light!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Truly, I must paint such a vision![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0][fName], I must say, you bring[n]me such dazzling ideas and feelings.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]My sights have broadened while[n]by your side.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You must continue this so I[n]can have such motivation all the time![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]By the way, the couple over[n]there seems to be giving us[n]quite a cold gaze.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Do they perhaps not enjoy the[n]reality of romance in the universe?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Please, take this to commemorate[n]today... My Space Memorial Day.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]What a wonderful date this was.[n]I thank you, [fName].[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][vp 8 2 0 4048 65535 0]Ah, I can hear my canvas[n]beckoning to me![n][f 1 3 65535][w][e]

