[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]So when exactly does this start?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am curious on why you would[n]wish to come here.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, speaking of which... It is starting.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I must say, it is rather...[n]intriquing to think about this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How small we are in this universe.[n]Insignificant. Barely causing a dent[n]in the way the world turns.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]We are very small.[e]
[s]That's a lot...[e]
[s]Are you good?[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Indeed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No matter what we do, we will[n]never be able to hold a light[n]to the way the universe runs.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]What? Too much for you to handle?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is merely the truth that we[n]will not be remebered in the grand[n]scheme of things.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I might be dark, but I am accurate.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Pessimism is the way to go when[n]you need to think logically on matters.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Either way, the universe is expansive.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Honestly, it is interesting to see[n]just how much there is in[n]scale to us in this projection.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]I do wonder if when I leave[n]I will have the same fate as[n]many in this world...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, nevermind that. Focus on[n]the show for now.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It seems it is over.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]With that, we are done here.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][vp 8 2 0 8051 65535 0]Let us go.[n][f 1 3 65535][w][e]

