[msg MSG_000_5_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8018 65535 0]I did not expect you to wish[n]to come to a place like a museum.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Was that artist's palace not[n]a museum as well? Is that why[n]we are here?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]It was.[e]
[s]It was Madarame.[e]
[s][f 0 8 2 1 2217]I forgot you were there...[clr 27][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]It was a rather blinding thing.[n]Honestly, I wanted to rid of it[n]when I first saw it.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Ah, right. That man.[n]I remember now.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do apologize. He was never an[n]important focus of mine.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Only once or twice to investigate.[n]It was only on Shido's will I even went.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Well, anyway, this type of place[n]is rather calming in a way.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Completely unlike the gaundy metaverse[n]version you got rid of months ago.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54404 65535 0]By the way...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Is that not the "Sayuri" that[n]everybody was on about before?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]It was Yusuke's wish.[e]
[s]It is.[e]
[s][f 0 8 2 1 2217]It shouldn't be here.[clr 27][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]That eccentric artist's?[n][f 1 3 65535][w][e]
[s]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The wish for a mother's recognition...[n]This seems to be a theme among you.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]I thought I recognized it walking in...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]No. It should not.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Yet another thing wrong with[n]this wretched world.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]No matter. It will be solved soon.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Let us go. It is getting late.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][vp 8 2 0 8054 65535 0]I will see you soon.[n][f 1 3 65535][w][e]

