[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Now that I think about it,[n]were you not here before?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I remember you being here when the[n]public first found out about Okumura.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]You were watching?[e]
[s]I was.[e]
[s]I forgot about that...[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Of course. I kept an eye on you[n]ever since I found out you were[n]the Phantom Thieves.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Honestly, it was kind of humorous[n]to see your reactions at the time.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]You are taking this seriously, correct?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You are right in front of his[n]true killer, after all.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It wasn't personal when I got[n]rid of him. He was merely a way to[n]trap you at the time.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He was starting to get a bit full[n]of himself, anyway. Shido was planning[n]on doing it long before you.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7040 65535 0]Shido... It still fills me with[n]anger to say his name.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Did you know he's alive in this[n]reality? What a joke...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But he won't be for long.[n]He will be gone soon.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]And you will make sure of it.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][vp 8 2 0 8072 65535 0]That's enough talking for now.[n]Let's go.[n][f 1 3 65535][w][e]

