[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Dummy Message[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems to be[n]rather content...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He has been quiet for[n]most of our time out...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]I have a special bond[n]Akechi...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Akechi]]
[s][vp 8 2 0 54425 65535 0]Goodnight, then.[n][f 1 3 65535][w][e]

