[msg MSG_GIFT_HELP_00]
[s]A ring inset with a heart-[n]shaped jewel. To captivate[n]a woman's heart.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_01]
[s]Slim bangle with a simple[n]and chic design. Can be[n]worn by men.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_02]
[s]A box of assorted flavors[n]of a popular snack. May[n]make a nice gift.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_03]
[s]A variety of ramen from[n]locales all over Japan.[n]For the noodle lover.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_04]
[s]Vitamins that completely[n]cover your health needs.[n]For the busy body.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_05]
[s]A famous brand of perfume[n]with a gentle scent. For a[n]sensual person in your life.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_06]
[s]Incense with a calming scent[n]that helps with relaxation.[n]For those who need to concentrate.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_07]
[s]An intensely red lipstick[n]worn by a popular model.[n]For the sweet tooth.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_08]
[s]A silk crêpe book cover with[n]a Japanese-style print on it.[n]For the traditional lady.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_09]
[s]A small fan with a[n]bright sakura pattern.[n]For the traditional lady.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_10]
[s]A palm-sized, colorful vase[n]made of glass. For the flower[n]lover in your life.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_11]
[s]Pudding made from uji[n]matcha green tea. For the[n]sweet tooth.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_12]
[s]Chocolate truffles made[n]with meticulous detail.[n]For the sweet tooth.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_13]
[s]A cake with refined texture[n]topped with coarse sugar.[n]For the sweet tooth.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_14]
[s]Body-building tools for[n]arms and legs. For the[n]exercise enthusiast.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_15]
[s]Sport sunglasses that cut[n]UV rays by 10%. For the[n]runner.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_16]
[s]A small cactus that looks[n]nice in an office setting.[n]For the desk jockey.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_17]
[s]A basket full of flowers from[n]all seasons. For the flower[n]lover in your life.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_18]
[s]The fragrance of roses for a[n]luxurious bath time. For the[n]special lady in your life.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_19]
[s]A star-shaped hand mirror[n]that's supposed to be lucky.[n]For a spiritual someone.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_20]
[s]A chic, black mug. For the[n]one who's married to the[n]desk.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_21]
[s]A set of 28 kitchen tools that[n]let you cook anything. For[n]the daily cook.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_22]
[s]An extremely difficult 3D[n]puzzle. For the desk worker[n]who needs a break.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_23]
[s]A pair of rings that are[n]puzzling beyond words. For[n]those who like a challenge.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_24]
[s]Cushion made of material[n]that sticks to the touch. For[n]the busy businessperson.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_25]
[s]The latest robot vacuum that[n]cleans automatically. For the[n]busy businessperson.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_26]
[s]Lightweight digital camera[n]using cutting-edge tech. For[n]the professional photog.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_27]
[s]A face massager that can slim[n]your face quickly. For those[n]within the spotlight.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_28]
[s]370,000 rotations per[n]second obliterate all plaque.[n]For the busy businessperson.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_29]
[s]Ultra-loud alarm clock to[n]wake up any sleepyhead.[n]For the busy businessperson.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_30]
[s]A palm-sized machine that[n]dispenses fragrance and[n]moisture. For desk workers.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_31]
[s]A 1/12 scale figurine made[n]with attention to detail. For[n]the bike lover in your life.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_32]
[s]A set of plushies of a popular[n]character. For the one who[n]likes rare finds.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_33]
[s]A set of badges of a super-[n]popular pop idol. For the[n]trendy friend.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_34]
[s]Katana keychain with a[n]dragon design. For the[n]young boy at heart.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_35]
[s]A superb fountain pen,[n]rereleased due to demand.[n]For the discerning eye.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_36]
[s]A postcard featuring a lovely[n]watercolor illustration. For[n]those with an aesthetic eye.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_37]
[s]An expensive-looking pen[n]case made of leather. For[n]the discerning eye.[n][f 1 2 65535][e]

[msg MSG_GIFT_HELP_38]
[s]Maybe I should wait[n]before giving any gifts.[n][f 1 2 65535][e]

[msg MSG_GIFT_TITLE_000]
[s]Gift-giving[n][e]

[sel SEL_GIFT_000_00 top]
[s][var 0][ref 0 0][var 1][ref 1 1][var 2][ref 2 2][var 3][ref 3 3][var 4][ref 4 4][var 5][ref 5 5][var 6][ref 6 6][var 7][ref 7 7][var 8][ref 8 8][var 9][ref 9 9][var 10][ref 10 10][var 11][ref 11 11][var 12][ref 12 12][var 13][ref 13 13][var 14][ref 14 14][var 15][ref 15 15][var 16][ref 16 16][var 17][ref 17 17][var 18][ref 18 18][var 19][ref 19 19][var 20][ref 20 20][var 21][ref 21 21][var 22][ref 22 22][var 23][ref 23 23][var 24][ref 24 24][var 25][ref 25 25][var 26][ref 26 26][var 27][ref 27 27][var 28][ref 28 28][var 29][ref 29 29][var 30][ref 30 30][var 31][ref 31 31]Never mind[ref 32 38][e]

[msg MND_CANCEL]
[s][vp 8 0 0 0 65535 0]Maybe I shouldn't[n]give any gifts for now...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_000]
[s][vp 8 0 0 0 65535 0]Maybe there's a way[n]to make sure Yusuke[n]has a good time...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_200]
[s][vp 8 0 0 0 65535 0]I already have a special bond[n]with Yusuke...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_000_5R_0]
[s][vp 8 0 0 0 65535 0]Oh, that's right, I have[n]something Yusuke might like...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_000_5R_1]
[s][vp 8 0 0 0 65535 0]Considering Yusuke, I feel like he'd[n]be delighted to receive something[n]that's [clr 2]aesthetically stimulating[clr 27]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_000_5R_2]
[s][vp 8 0 0 0 65535 0]This might make[n]a good present...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_001]
[s][vp 8 0 0 0 65535 0]I gave [var 30]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_002 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]This is for... me? To think I'd be given[n]an accessory of this kind from you,[n][fName].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, it isn't too gaudy—I feel as if[n]I could wear this for all sorts of occasions.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thank you, [fName]. I'll care for[n]this well.[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_003]
[s][vp 8 0 0 0 65535 0]It feels like I was able[n]to touch Yusuke's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_004_004 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]What the...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I've been struck with a bolt of inspiration![n]This color... It's... beautiful![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I must thank you, [fName]. I feel as[n]if I can further my art even more thanks[n]to you.[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_005]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Yusuke's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_004_006 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]This—! [fName], are you absolutely[n]sure that I can have this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I truly appreciate it, [fName]...[n]Now I can survive for another three days![n][f 1 3 65535][w][e]

[msg MND_GIFT_004_007]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Yusuke's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_004_008 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]This is... for me?[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]I will gladly accept this. Thank you, [fName].[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_009]
[s][vp 8 0 0 0 65535 0]It feels like I touched[n]Yusuke's heart a little...[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_010 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 35 5 100]What's this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]This isn't something I especially need...[n]but I appreciate the thought. Thank you.[n][f 1 3 65535][w][e]

[msg MND_GIFT_004_011]
[s][vp 8 0 0 0 65535 0]It feels like I didn't[n]really impress Yusuke much[n]with my gift for him...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_000]
[s][vp 8 0 0 0 65535 0]Maybe there's a way[n]to make sure Ryuji[n]has a good time...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_200]
[s][vp 8 0 0 0 65535 0]I already have a special bond[n]with Ryuji...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_000_5R_0]
[s][vp 8 0 0 0 65535 0]Oh, that's right, I have[n]something Ryuji might like...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_000_5R_1]
[s][vp 8 0 0 0 65535 0]Considering Ryuji, I feel like he'd[n]be happy to receive something[n][clr 2]fitting for his age[clr 27]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_000_5R_2]
[s][vp 8 0 0 0 65535 0]This might make[n]a good present...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_001]
[s][vp 8 0 0 0 65535 0]I gave [var 30]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_002 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Whoa, there's a shit-ton in here! Oh man,[n]I dunno which one to try first![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I ain't gonna be worryin' about midnight[n]snacks for a LONG time with this! Thanks,[n][fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_003]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Ryuji's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_004 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're... you're givin' this to me? For real!?[n]That's crazy nice, dude![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ain't this the latest model too? I just saw[n]a commercial for it! My mom's been[n]dyin' to get one...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're lookin' at the new Sakamoto[n]family pet—all thanks to you! Seriously,[n]thank you, [fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_005]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Ryuji's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_006 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]H-Holy... Are you sure I can have this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thanks, dude! I'm gonna start trainin'[n]with these today![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_007]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Ryuji's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_008 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're givin' this to ME!? Thanks, man![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_009]
[s][vp 8 0 0 0 65535 0]It feels like I touched[n]Ryuji's heart a little...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_010 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 35 5 100]I mean, I don't hate it or nothin'...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Welp, thanks anyway.[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_011]
[s][vp 8 0 0 0 65535 0]It feels like I didn't[n]really impress Ryuji[n]much with my gift for him...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_012 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You have no idea how bad I wanted this![n]I gave up on it 'cause my allowance ain't[n]high enough to afford it![n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am so pumped right now! I swear[n]I'll take good care of it! Thanks![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_013]
[s][vp 8 0 0 0 65535 0]It feels like I was able[n]to touch Ryuji's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_014 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh man, this is sooo cool! I totally wanted[n]one of these when I was little![n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You got me feelin' like a kid all over[n]again! Thanks, [fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_015]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Ryuji's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_026_000]
[s][vp 8 0 0 0 65535 0]Maybe there's a way[n]to make sure Akechi[n]has a good time...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_200]
[s][vp 8 0 0 0 65535 0]I already have a special bond[n]with Akechi...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_000_5R_0]
[s][vp 8 0 0 0 65535 0]Oh, that's right, I have[n]something Akechi might like...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_000_5R_1]
[s][vp 8 0 0 0 65535 0]Considering Akechi, I feel[n]like he may appreciate[n]something [clr 2]useful to him[clr 27]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_000_5R_2]
[s][vp 8 0 0 0 65535 0]This might make[n]a good present...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_001]
[s][vp 8 0 0 0 65535 0]I gave [var 30]...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_002 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're just... giving this to me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I've been feeling rather tired lately, so[n]I'm quite pleased with this. Thanks.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_003]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Akechi's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_026_004 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Hm? Oh, you're... Are you sure you want[n]to give me something so expensive?[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Honestly, I've been getting neglectful[n]with the tidying up, so this will very[n]useful...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thanks. I'll give it a whirl the moment[n]I get home.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_005]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Akechi's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_026_006 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]What's this? An accessory?[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hahaha, you always surpass my[n]expectations. To think I'd receive[n]a gift like this from you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You truly fascinate me. I'll happily accept[n]your gift.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_007]
[s][vp 8 0 0 0 65535 0]It feels like I was able[n]to touch Akechi's heart![n][f 1 3 65535][w][e]

[msg MND_GIFT_026_008 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]This is for me? Thanks.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_009]
[s][vp 8 0 0 0 65535 0]It feels like I touched[n]Akechi's heart a little...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_010 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 35 5 100]What's this? Umm... Well, I should[n]thank you.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_011]
[s][vp 8 0 0 0 65535 0]It feels like I didn't[n]really impress Akechi[n]much with my gift for him...[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_012 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Hahaha, you truly are intriguing.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Never would I have imagined that you'd[n]give me this sort of gift—though I do admit,[n]my public life does make it a useful one.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thank you. I'll try it out once I get home.[n][f 1 3 65535][w][e]

[msg MND_GIFT_026_013]
[s][vp 8 0 0 0 65535 0]It feels like I really[n]captured Akechi's heart![n][f 1 3 65535][w][e]

[msg MND_RANK_UP_ANNOUNCE_04]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Yusuke[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MND_RANK_UP_ANNOUNCE_07]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Ryuji[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MND_RANK_UP_ANNOUNCE_18]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Mishima[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MND_RANK_UP_ANNOUNCE_26]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MND_RANK_NOT_ANNOUNCE_04]
[s][vp 8 0 0 0 65535 0]I don't think my bond with[n]Yusuke will deepen just yet...[n][f 1 3 65535][w][e]

[msg MND_RANK_NOT_ANNOUNCE_07]
[s][vp 8 0 0 0 65535 0]I don't think my bond with[n]Ryuji will deepen just yet...[n][f 1 3 65535][w][e]

[msg MND_RANK_NOT_ANNOUNCE_18]
[s][vp 8 0 0 0 65535 0]I don't think my bond with[n]Mishima will deepen just yet...[n][f 1 3 65535][w][e]

[msg MND_RANK_NOT_ANNOUNCE_26]
[s][vp 8 0 0 0 65535 0]I don't think my bond with[n]Akechi will deepen just yet...[n][f 1 3 65535][w][e]

[msg MND_RANK_MAX_ANNOUNCE_04]
[s][vp 8 0 0 0 65535 0]I have a special bond[n]with Yusuke...[n][f 1 3 65535][w][e]

[msg MND_RANK_MAX_ANNOUNCE_07]
[s][vp 8 0 0 0 65535 0]I have a special bond[n]with Ryuji...[n][f 1 3 65535][w][e]

[msg MND_RANK_MAX_ANNOUNCE_18]
[s][vp 8 0 0 0 65535 0]I have a special bond[n]with Mishima...[n][f 1 3 65535][w][e]

[msg MND_RANK_MAX_ANNOUNCE_26]
[s][vp 8 0 0 0 65535 0]I have a special bond[n]with Akechi...[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_002_SCHOOL [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Whoa, there's a shit-ton in here! Oh man,[n]I dunno which one to try first![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I ain't gonna be worryin' about midnight[n]snacks for a LONG time with this! Thanks,[n][fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_002_GYM [Ryuji]]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Whoa, there's a shit-ton in here! Oh man,[n]I dunno which one to try first![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I ain't gonna be worryin' about midnight[n]snacks for a LONG time with this! Thanks,[n][fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_004_SCHOOL [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're... you're givin' this to me? For real!?[n]That's crazy nice, dude![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ain't this the latest model too? I just saw[n]a commercial for it! My mom's been[n]dyin' to get one...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're lookin' at the new Sakamoto[n]family pet—all thanks to you! Seriously,[n]thank you, [fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_004_GYM [Ryuji]]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're... you're givin' this to me? For real!?[n]That's crazy nice, dude![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ain't this the latest model too? I just saw[n]a commercial for it! My mom's been[n]dyin' to get one...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're lookin' at the new Sakamoto[n]family pet—all thanks to you! Seriously,[n]thank you, [fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_006_SCHOOL [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]H-Holy... Are you sure I can have this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thanks, dude! I'm gonna start trainin'[n]with these today![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_006_GYM [Ryuji]]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]H-Holy... Are you sure I can have this?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Thanks, dude! I'm gonna start trainin'[n]with these today![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_008_SCHOOL [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're givin' this to ME!? Thanks, man![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_008_GYM [Ryuji]]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You're givin' this to ME!? Thanks, man![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_010_SCHOOL [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 35 5 100]I mean, I don't hate it or nothin'...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Welp, thanks anyway.[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_010_GYM [Ryuji]]
[s][bup 0 2 603 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 35 5 100]I mean, I don't hate it or nothin'...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Welp, thanks anyway.[n][f 1 3 65535][w][e]

[msg MND_GIFT_007_012_SCHOOL [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You have no idea how bad I wanted this![n]I gave up on it 'cause my allowance ain't[n]high enough to afford it![n][f 1 3 65535][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am so pumped right now! I swear[n]I'll take good care of it! Thanks![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_012_GYM [Ryuji]]
[s][bup 0 2 604 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You have no idea how bad I wanted this![n]I gave up on it 'cause my allowance ain't[n]high enough to afford it![n][f 1 3 65535][w][e]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am so pumped right now! I swear[n]I'll take good care of it! Thanks![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_014_SCHOOL [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 39 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh man, this is sooo cool! I totally wanted[n]one of these when I was little![n][f 1 3 65535][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You got me feelin' like a kid all over[n]again! Thanks, [fName]![n][f 1 3 65535][w][e]

[msg MND_GIFT_007_014_GYM [Ryuji]]
[s][bup 0 2 604 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 39 5 100]Huh? Wait—this is seriously for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh man, this is sooo cool! I totally wanted[n]one of these when I was little![n][f 1 3 65535][w][e]
[s][bup 0 2 601 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You got me feelin' like a kid all over[n]again! Thanks, [fName]![n][f 1 3 65535][w][e]

