[sel SEL_001_0_0 top]
[s]Take a walk with Makoto[ref 0 7][e]
[s]Go to the beach with Ann[ref 1 8][e]
[s]Go see Kawakami[ref 2 9][e]
[s]Go meet with Hifumi[ref 3 10][e]
[s]Hang out with the guys[ref 4 11][e]
[s]See the sights with Yusuke[ref 5 12][e]
[s]Hang out with Ryuji[ref 6 13][e]
[s]Take a walk with Mishima[ref 7 14][e]

[msg GENERIC_HELP_01]
[s]Should I spend time[n]alone with Makoto...?[n][e]

[msg GENERIC_HELP_02]
[s]Should I spend time[n]alone with Ann...?[n][e]

[msg GENERIC_HELP_03]
[s]Should I spend time[n]alone with Kawakami...?[n][e]

[msg GENERIC_HELP_04]
[s]Should I spend time[n]alone with Hifumi...?[n][e]

[msg GENERIC_HELP_05]
[s]Should I spend time[n]with Ryuji and Mishima...?[n][e]

[msg GENERIC_HELP_06]
[s]Should I spend time[n]alone with Yusuke...?[n][e]

[msg GENERIC_HELP_07]
[s]Should I spend time[n]alone with Ryuji...?[n][e]

[msg GENERIC_HELP_08]
[s]Should I spend time[n]alone with Mishima...?[n][e]