[msg GENERIC_HELP_01]
[s]Should I spend time[n]alone with Makoto...?[n][e]

[msg GENERIC_HELP_02]
[s]Should I spend time[n]alone with Haru...?[n][e]

[msg GENERIC_HELP_03]
[s]Should I spend time[n]alone with Ann...?[n][e]

[msg GENERIC_HELP_04]
[s]Should I spend time[n]alone with Kawakami...?[n][e]

[msg GENERIC_HELP_05]
[s]Should I spend time[n]with Ryuji and Mishima...?[n][e]

[msg GENERIC_HELP_06]
[s]Should I spend time[n]alone with Yusuke...?[n][e]

[msg GENERIC_HELP_07]
[s]Should I spend time[n]alone with Ryuji...?[n][e]

[msg GENERIC_HELP_08]
[s]Should I spend time[n]alone with Mishima...?[n][e]

[sel SEL_001_0_0 top]
[s]Makoto[ref 0 5][e]
[s]Haru[ref 1 6][e]
[s]Ann[ref 2 7][e]
[s]Kawakami[ref 3 8][e]
[s]Ryuji and Mishima[ref 4 9][e]
[s]Yusuke[ref 5 10][e]
[s]Ryuji[ref 6 11][e]
[s]Mishima[ref 7 12][e]