[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have wanted to ride this for a while,[n]but I have never been able to.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do apologize for using you[n]as a reason to indulge myself.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Indulge all you like.[e]
[s]I feel used.[e]
[s]At least the view is nice.[n][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]Well, if it is accepted, then I shall.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Of course, with limits.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Would you feel better if I told you[n]I would only come up here with you?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]Indeed. The city from up here[n]looks rather small.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It gives us quite a different[n]perspective on our usual life.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Now that I'm out of my slump,[n]I need to make up for the[n]time I wasn't able to paint.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have learned about the human[n]heart and the inner workings.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enable to continue my journey,[n]I must learn more. To do this,[n]new experiences are needed.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]After all, is it not true that[n]experiences lead to lessons of the heart?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]I believe so.[e]
[s]What...?[e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]I am delighted that you agree.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What...?[n][f 1 3 65535][w][e]

[msg MSG_0010_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well then, I shall reiterate my[n]prior promise to you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]I'll extend my assistance to[n]you, should you ever stumble.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I shall also stay by your side,[n]just as you have with me.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0]......[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke seems to be thinking...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 20 65535 0][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]Speaking of new experiences... there[n]is one at which you brought into[n]existence when we went to Mementos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Relationships like these may also[n]bring about plenty of new experiences[n]and unlock more facets of the heart.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So I do hope you are still fully[n]into the idea of one with me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am fully serious about this, after all.[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]I am fully serious.[e]
[s]I do love you.[e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]Good.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 24 65535 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]I shall admit, I did not expect[n]this forwardness.[n][f 1 3 65535][w][e]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But... I love you, too, [fName].[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]By the way... people usually call[n]their lovers nicknames in[n]relationships, correct?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Should I be calling you "babe"[n]or something like that now...?[n]Or maybe "honey?" "Darling?"[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ride Announcement]]
[s][vp 8 0 0 0 65535 0]Thank you for enjoying our Ferris[n]wheel experience. The gondola will[n]arrive at the platform shortly.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh. It seems the ride is[n]almost over.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was so focused on you that[n]I barely focused on the actual[n]Ferris wheel experience.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Do you remember what I said[n]before about new experiences, [fName]?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perhaps we could get into one[n]of those new experiences now?[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]I'm down to try.[e]
[s]Only one new experience?[e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sadly, there is only time for one.[n]But experiences are best lived[n]one at a time.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 20 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Like with the heart before, you may[n]have to guide me. I am inexperienced.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]I spent a long time with Yusuke...[n][f 1 3 65535][w][e]

[msg MND_027_0_0]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]It's getting late... I[n]should probably walk him[n]to the station...[n][f 1 3 65535][w][e]

