[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke seems content.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 5]We talked for quite a while[n]about art and aesthetics.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Yusuke[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][vp 8 2 0 4071 65535 0]Speaking with you seems to clear my mind.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I must paint this emotion...[n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]I walked Yusuke to the station...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke seems rather pleased.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 5]We talked for quite a while[n]about art and aesthetics.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Yusuke[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][vp 8 2 0 4071 65535 0]My painting has been going quite[n]nicely since we started doing this.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Let us continue having calmer days like this.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]I walked Yusuke to the station...[n][f 1 3 65535][w][e]

