[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I must ask, [fName], why is it that[n]you've stayed with me all this time?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It must have been difficult to handle my ravings.[n][f 1 3 65535][w][e]

[msg MND_900_0_0]
[s][vp 8 0 0 0 65535 0]I should choose my words carefully...[n][f 1 3 65535][w][e]

[msg MND_901_0_0]
[s][vp 8 0 0 0 65535 0]I should choose my[n]words carefully...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I'm already [clr 2]in a relationship with[n]someone else[clr 27]...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Is there a certain reason?[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s][f 0 8 2 1 2217]Because we're friends.[clr 27][e]
[s]Because I like you.[e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 15 5 1009]I understand. Friendship is truly a wonderful thing.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Through it, I have found the rays of hope[n]in the darkness, which I can[n]now visualize with my brush.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]I thank you, [fName].[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 104 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]My apologies. I'm afraid I don't understand.[n]What do you mean...?[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]I see us as close friends.[e]
[s]I see you as more than a friend.[bitflag 0 1 717 1][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]Ah, yes, I see. I share the same sentiment.[n][f 1 3 65535][w][e]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Truly, we are close. Even moreso[n]now that you've helped me in my endeavors.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]I am in your debt, [fName].[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 2 0 4087 65535 0]......[n][f 1 3 65535][w][e]
[s][bup 0 5 101 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I see. To think that you as well...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 1 300 1][vp 8 2 0 4048 65535 0]Very well, then. I accept.[n][f 1 3 65535][w][e]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have learned through you my way in art.[n]It is only fitting to see this through[n]to the end with you in life as well.[n][f 1 3 65535][w][e]
 [e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]I'm in a relationship with Yusuke...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]There's no turning back now...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]I can sense Shadows in the area...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We should leave Mementos...[n][f 1 3 65535][w][e]

