[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]The other exhibits in the competition[n]were all wonderful as well.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]It makes me all the more glad[n]to have won myself amongst[n]all these talented artists.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]What'll you be doing now?[e]
[s]It was a close match.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0]Paint, of course.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0]Indeed. I was lucky to have[n]gained the favor of the judges.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0]I know that I have said this prior,[n]but I must reiterate.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]I thank you, [fName], for staying by me.[n]It is because of you that my slump[n]is no more.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0]Now that I'm out of my slump,[n]I need to make up for the[n]time I wasn't able to paint.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]I do hope you will continue to[n]watch me grow as an artist.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]I will.[e]
[s]Will there be more slumps?[e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]Thank you, [fName].[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]It is natural for an artist[n]to have rough days.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]When that time comes, I shall[n]ask for your assistance once again.[n][f 1 3 65535 1 1][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]Well, it seems like the exhibit[n]is beginning to end soon.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][vp 8 2 0 4050 65535 0]Shall we head off?[n][f 1 3 65535][w][e]

