[sel SEL_001_0_0 top]
[s]What are we doing here?[e]
[s][f 0 8 2 1 2217]Why are we in a boat?[clr 27][e]
[s][f 0 8 2 1 2217]I should bring a date here.[clr 27][e]

[msg MSG_004_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 7 300 1][vp 8 2 0 4040 65535 0][coop 5 5 5]Date...? So you're dating somebody? You should have[n]mentioned this sooner![n][f 1 3 65535][w][e]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have missed the opportunity for a truly[n]wonderful subject...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That aside, I must thank you for your[n]help today. This is the ideal location[n]for my next motif.[n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s][f 0 8 2 1 2217]Seems we've been caught.[e]
[s]Well, this is awkward...[e]

[msg MSG_036_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 5 10 5]For what would we be caught doing?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What are you talking about?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][f 4 10 65535 0 0][vp 8 2 0 4050 65535 0]Ah well... Come, it is about time[n]we return home.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Please row us back to shore, [fName].[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Yusuke]]
[s][vp 8 2 0 4063 65535 0]Farewell.[n][f 1 3 65535][w][e]

