[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji seems happy.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 4]We talked for quite a while[n]about track and our relationship.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Ryuji[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][vp 8 2 0 7048 65535 0]This was nice. Let's do this again, dude![n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]I walked Ryuji to the station...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji seems content.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 4]We talked for quite a while[n]about track and our relationship.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Ryuji[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][vp 8 2 0 7048 65535 0]I'm startin' to feel better about this.[n]Thanks, dude![n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]I walked Ryuji to the station...[n][f 1 3 65535][w][e]

