[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]So this is where you make all[n]of your tools for infiltration, correct?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Why don't you make some?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]What should I make?[e]
[s]Right now?[e]
[s]This is supposed to be a date.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]Why don't you surprise me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Make it good. We will need[n]to use this in the palace.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Would there be any other time?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Of course now.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8018 65535 0]Did you expect this to be some[n]sort of warm and fuzzy time?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I said I would humor you, but I[n]will not let it get in the way[n]of your productivity towards our goal.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So what are you waiting for?[n]Get to it.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]So this is how you work...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Rather interesting, to say the least...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I believe I have the gist now.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Are you satisfied?[e]
[s]How does it look?[e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]It is mediocre, but it will do.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is only a couple lockpicks.[n]It is not like they are essential[n]to the infiltration.[n][f 1 3 65535][w][e]

[msg MSG_0010_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Now that you've been productive[n]I guess I will do what you wished.[n][f 1 3 65535][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You wanted a date, correct?[n]Fine, but I am not too knowledgeable[n]in such avenues.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][vp 8 2 0 8156 65535 0]Let us stay for a bit longer.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s]I spent a long time with Akechi.[n][f 1 3 65535][w][e]
[s]......[n][f 1 3 65535][w][e]
[s]It is getting late. I should[n]take him to the station.[n][f 1 3 65535][w][e]

