[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 805 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]To think even in this form you[n]win against me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You learn quickly, unfortunately.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Satisfied with the rematch?[e]
[s]I am the leader, after all.[e]
[s]Are we continuing?[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 812 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Yes. I believe I got all I[n]needed from this exchange.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Rather proud of yourself, aren't you?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]However, you are correct. You are[n]the leader of the Phantom Thieves[n]for a reason.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 814 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Do you want one of us to die?[n]That is what will happen if we[n]continue this.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Maruki's takedown is essential.[n]We cannot go any further than this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]We honestly should not have done[n]this anyway, but I had to make[n]sure it was done...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]...We're done here. Let's go.[n][f 1 3 65535][w][e]

