[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems focused.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 5]He mostly wanted me to be[n]productive and make tools...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][vp 8 2 0 4071 65535 0]This was a productive day.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Make sure to continue working.[n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]I walked Akechi to the station...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Akechi seems rather pleased.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][coop 7 10 5]He mostly wanted me to be[n]productive and make tools...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 8 2 0 4071 65535 0]This was a productive day.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We should continue doing this.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]I walked Akechi to the station...[n][f 1 3 65535][w][e]

