[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]This is a good enough place[n]to speak privately.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I have, unfortunately, lost.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]This means we need to speak[n]on certain matters, does it not?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]I like you.[e]
[s]It does...[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]...You are quite forward.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 13 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8161 65535 0]You are aware I do hate you, correct?[n]Does this not feel like a futile[n]attempt for whatever this is?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]I cannot fathom what it is[n]you expect from revealing this.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]I want to be closer.[e]
[s]A relationship.[e]
[s]I don't know either.[e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]What good would that do?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You still insist on making[n]things difficult.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You did this without a clear goal?[n]You are more emotional than[n]I thought.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Ever since the beginning, you[n]have been a thorn in my side.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You constant surpassing of me. Your[n]ability to see through me. It is[n]infuriating. Frustrating.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54404 65535 0]And things are only more compicated[n]now... with Maruki and this[n]dreaded reality if his.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Do you seriously think this[n]is a good idea?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]I don't think you hate me.[e]
[s]It can work out.[e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Do you now? Such a poor delusion[n]you have there.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8161 65535 0]Your confidence in such delusions[n]is honestly pitiful.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But I did say I would humor you.[n][f 1 3 65535][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]So I will. I will humor you.[n]But on one condition...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Condition?[e]
[s]What is it?[e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][vp 8 2 0 54450 65535 0]You will not let this illusion[n]you have effect your decisions.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I will not allow you to be[n]thrown off by such pitiful emotions[n]and do something you regret.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]What would this effect?[e]
[s]I understand.[e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Do not worry about that.[n]Just focus on what you need[n]to do and this will work out.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54469 65535 0]Good. Then this can happen as you wish.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Now then, what do you wish to do?[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Show me why you feel so[n]strongly about this, [fName].[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s]I spent a long time with Akechi.[n][f 1 3 65535][w][e]
[s]......[n][f 1 3 65535][w][e]
[s]It is getting late. I should[n]take him to the station.[n][f 1 3 65535][w][e]

