[msg MSG_000_3_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ざわつく声)[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Post-Festival MC]]
[s]All right, that was a great performance[n]by the dance club![n][f 1 3 65535][w][e]
[s]Everybody give them another[n]round of applause![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]It seems that I was unable to[n]focus on the performance.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The looming threat of Akechi[n]has been running throughout my[n]thoughts the entire time.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]We'll be okay.[e]
[s]It doesn't look good.[e]
[s][f 0 8 2 1 2217]Let's forget about it for now.[clr 27][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]When you are so confident[n]it is difficult to contradict.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]...Yes. It does not.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]I understand. We are here to[n]enjoy our time, not to sulk in threats.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]At any rate, do you know what[n]exactly to do in these sorts of[n]gatherings? Is there a guide of sorts?[n][n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Post-Festival MC]]
[s]And now, it's time for your[n]favorite Shujin tradition:[n]the Student Sharing Special![n][f 1 3 65535][w][e]
[s]Round of applause, everyone![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sharing Special?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Would you happen to know what this is?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Post-Festival MC]]
[s]All right, who has something to say?[n]Anyone, anyone!?[n][f 1 3 65535][w][e]
[s]No? I'll just have to pick someone then![n][f 1 3 65535][w][e]
[s]How about...[n][f 1 3 65535][w][e]
[s]The good sir over there![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 4 2 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]...Me?[n][f 1 3 65535][w][e]

[msg MND_015_0_0]
[s][vp 8 0 0 0 65535 0]It seems he thinks Yusuke[n]is from Shujin...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Post-Festival MC]]
[s]Well then, come on up![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 4 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But I am not-[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Post-Festival MC]]
[s]Now, now! You're not shy, are you!?[n][f 1 3 65535][w][e]
[s]Come, come. Everyone's waiting![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 5 2 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]It seems that they will not[n]hand me any other options...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Post-Festival MC]]
[s]And what is your name?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yusuke Kitagawa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am still not a part of this school.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Post-Festival MC]]
[s]Kitagawa-kun. I see![n][f 1 3 65535][w][e]
[s]If you aren't from Shujin, then[n]where do you go?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Kosei High School...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Post-Festival MC]]
[s]Kosei!? Well, we certainly got a[n]prestigous one here, now, don't we?[n][f 1 3 65535][w][e]
[s]Well, it would be nice to have some[n]outside perspective on this next[n]question we have here, then.[n][f 1 3 65535][w][e]
[s]Do you think the Phantom Thieves[n]are really Shujin students?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1][vp 8 0 0 0 65535 0]E-Excuse me...!?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](観衆のざわめき)[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Post-Festival MC]]
[s]We're all dying to know what[n]Akechi-kun was going to say about[n]their true identities.[n][f 1 3 65535][w][e]
[s]So, are they from Shujin? What do you[n]think, Kitagawa-kun?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0]Yes... What do I think, indeed...?[n][f 1 3 65535][w][e]

[msg MND_037_5_0]
[s][vp 8 0 0 0 65535 0]Yusuke is in trouble...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I need to change[n]the subject...[n][f 1 3 65535][w][e]

[msg MSG_036_5_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, you see...[n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s]Are you in a relationship!?[e]
[s]I love you![e]

[msg MSG_039_0_0 [Yusuke]]
[s][bup 0 5 24 2 0][f 4 10 65535 0 0][vp 8 2 0 4046 65535 0]A... A what!?[n][f 1 3 65535][w][e]

[msg MSG_039_5_0 [Post-Festival MC]]
[s]Oooh, an interesting question from the crowd![n][f 1 3 65535][w][e]
[s]And it seems a lot of the girls[n]in the crowd want the same answer![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 5 301 1][vp 8 2 0 4074 65535 0]*cough* Y-You...![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Post-Festival MC]]
[s]Now this is drama! A boy caught[n]in the throes of bittersweet youth![n]A stunning confession of love![n][f 1 3 65535][w][e]
[s]And a rather interesting one at that![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ヤジ)[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Post-Festival MC]]
[s]I think it was him![n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Yusuke]]
[s][bup 0 5 24 2 0][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0]I do not believe we truly[n]need to do something so abrupt-![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Post-Festival MC]]
[s]Sooo, Kitagawa-kun! What's your[n]relation to this guy?[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Yusuke]]
[s][bup 0 5 23 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Do we have to go so[n]thoroughly into this...?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Post-Festival MC]]
[s]My, he's red as a beet![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Post-Festival MC]]
[s]But I'm a kind man. It hurts my heart[n]to bully to this extent![n][f 1 3 65535][w][e]
[s]Well, did you all enjoy our[n]drama-filled questioning? Thank you[n]very much, Kitagawa-kun![n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ブーイング)[n][f 1 3 65535][w][e]

