[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]That... just happened.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For once, I truly have no words.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 3 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]And you saying such things in[n]front of everyone. I cannot begin[n]to process it...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]You were in trouble.[clr 27][e]
[s][f 0 8 2 1 2217]I couldn't ignore you.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 4 2 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]That is true. I was hesitating.[n]However, that...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]So this was a way of saving me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I believe there could have been[n]better options...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, it did get me out of a[n]rather precarious position...[n]No matter how... flustering it was.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]So for that, I do have to thank[n]you for getting me out of it.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For as strange as the methods you[n]use are, you are rather helpful, [fName].[n][f 1 3 65535][w][e]
[s][bup 0 5 20 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is nice to be with someone as[n]dependable as you. Truly, you are...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 4 300 1]Well, nevermind that.[n][f 1 3 65535][w][e]
[s][bup 0 5 24 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We don't need to get into topics[n]which hast been established plenty ago.[n][f 1 3 65535][w][e]

[sel SEL_008_5_0 top]
[s][f 0 8 2 1 2217]You're dependable as well.[clr 27][e]
[s][f 0 8 2 1 2217]I feel the same way.[clr 27][e]

[msg MSG_008_7_0 [Yusuke]]
[s][bup 0 5 21 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 7 10 4]Such ways with words.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]You speak like a master artist paints.[n]Eloquently. Your charm is not lacking[n]in the slightest.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]It has been a truly wild adventure,[n]but I did actually enjoy this[n]time with you at the party.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I never come to events such as this.[n]I am usually inside, painting my next piece.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You made this a magnificent experience.[n]Unique... but magnificent.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I ended up getting something during[n]the festival which I would like to[n]have over to you.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do hope you enjoy it.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]It looks delicious.[clr 27][e]
[s][f 0 8 2 1 2217]I can't wait to eat it.[clr 27][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 7 15 4]I am glad it satisfies you.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 1 2 0][f 4 10 65535 0 0][vp 8 2 0 4050 65535 0]Would you like to head off?[n]It is getting rather late.[n][f 1 3 65535][w][e]

