[msg MSG_000_3_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ざわつく声)[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Post-Festival MC]]
[s]All right, that was a great performance[n]by the dance club![n][f 1 3 65535][w][e]
[s]Everybody give them another[n]round of applause![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 3 2 0][f 4 10 65535 0 0][vp 8 2 0 19028 65535 0]That was... more boring than[n]I thought it would be...[n][f 1 3 65535][w][e]
[s][bup 0 111 1 2 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]They seemed to be having[n]fun, though![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][bup 0 111 3 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was a bit distracted[n]most of the time, to be honest...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 19044 65535 0][f 4 10 65535 0 0]Did something happen with Akechi earlier?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I saw you walk away when[n]he left the stage...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Just some private matters.[e]
[s]Nothing good...[e]
[s][f 0 8 2 1 2217]Nothing to worry about for now.[clr 27][e]

[msg MSG_005_0_0 [Mishima]]
[s][bup 0 111 3 2 0][f 4 10 65535 0 0][vp 8 2 0 19130 7 0][coop 3 5 1011]Oh... I see.[n][f 1 3 65535][w][e]
[s][bup 0 111 0 2 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]I won't ask about it.[n]Just know I'm rooting for you![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][bup 0 111 0 2 0][f 4 10 65535 0 0][vp 8 2 0 19025 65535 0]I see...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][bup 0 111 0 2 0][vp 8 2 0 19018 65535 0][f 4 10 65535 0 0][coop 3 10 1011]All right. I understand.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I hope it all works out[n]whatever it is![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Post-Festival MC]]
[s]And now, it's time for your[n]favorite Shujin tradition:[n]the Student Sharing Special![n][f 1 3 65535][w][e]
[s]Round of applause, everyone![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Mishima]]
[s][bup 0 111 3 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh? This again?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I believe they did this[n]last year, too.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Post-Festival MC]]
[s]All right, who has something to say?[n]Anyone, anyone!?[n][f 1 3 65535][w][e]
[s]No? I'll just have to pick someone then![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Mishima]]
[s][bup 0 111 0 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]From what I remember,[n]this one wasn't much.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19055 65535 0]Should we go? Maybe get[n]something to eat as usual?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Post-Festival MC]]
[s]How about...[n][f 1 3 65535][w][e]
[s]The very generic-looking guy over there![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Mishima]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 111 7 301 1][vp 8 2 0 19042 65535 0]What!? Generic!?[n][f 1 3 65535][w][e]
[s][bup 0 111 4 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wait...! Hold on...![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Post-Festival MC]]
[s]Well then, come on up![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][bup 0 111 5 2 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]W-What do I do...?[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]You have to go up now.[e]
[s]You can't ignore him.[e]
[s]It's your time to shine.[e]

[msg MSG_021_0_0 [Mishima]]
[s][bup 0 111 3 2 0][vp 8 2 0 19027 65535 0][f 4 10 65535 0 0]D-Do I have to...?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Mishima]]
[s][bup 0 111 3 2 0][vp 8 2 0 19081 65535 0][f 4 10 65535 0 0]I can't, but...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Mishima]]
[s][bup 0 111 3 2 0][vp 8 2 0 19038 65535 0][f 4 10 65535 0 0]I don't think I want to this way...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Post-Festival MC]]
[s]Now, now! You're not shy, are you!?[n][f 1 3 65535][w][e]
[s]Come, come. Everyone's waiting![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Mishima]]
[s][bup 0 111 3 2 0][vp 8 2 0 19082 65535 0][f 4 10 65535 0 0]There's no choice...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Post-Festival MC]]
[s]And what is your name?[n][f 1 3 65535][w][e]

[msg MSG_027_7_0 [Mishima]]
[s][bup 0 111 3 65535 0][vp 8 2 0 19104 65535 0][f 4 10 65535 0 0]Y-Yuuki Mishima...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Post_Festival MC]]
[s]Wow! He looks even more generic[n]up close![n][f 1 3 65535][w][e]
[s]I'm sure someone like you has[n]seen many things in the background![n][f 1 3 65535][w][e]
[s]Do you have anything you would[n]like to share with us, Mishima-kun?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Mishima]]
[s][bup 0 111 3 2 0][vp 8 2 0 19032 65535 0][f 4 10 65535 0 0]N-No... Not really...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Post-Festival MC]]
[s]Here, I'll give you a question...[n][f 1 3 65535][w][e]
[s]Do you think the Phantom Thieves[n]are really Shujin students?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Mishima]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 111 7 301 1][vp 8 2 0 19040 65535 0]Wh-what!?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](観衆のざわめき)[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Post-Festival MC]]
[s]We're all dying to know what[n]Akechi-kun was going to say about[n]their true identities.[n][f 1 3 65535][w][e]
[s]Some people theorize that they go[n]to our very school...[n][f 1 3 65535][w][e]
[s]So, are they from Shujin? What do you[n]think, Mishima-kun?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Mishima]]
[s][bup 0 111 4 2 0][vp 8 2 0 19022 65535 0][f 4 10 65535 0 0]I... Um... You see...[n][f 1 3 65535][w][e]

[msg MND_038_5_0]
[s][vp 8 0 0 0 65535 0]Mishima is in trouble...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I need to change[n]the subject...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Mishima]]
[s][bup 0 111 4 2 0][f 4 10 65535 0 0][vp 8 2 0 19018 65535 0][f 4 10 65535 0 0]Well...[n][f 1 3 65535][w][e]

[sel SEL_040_5_0 top]
[s]Do you have a boyfriend!?[e]
[s]You're adorable![e]
[s]I've always loved you![e]

[msg MSG_041_0_0 [Mishima]]
[s][bup 0 111 24 65535 0][vp 8 2 0 19040 65535 0][f 4 10 65535 0 0]What? Huh...? HUH!?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Post-Festival MC]]
[s]It seems we have a question[n]from the crowd![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Mishima]]
[s][bup 0 111 24 65535 0][vp 8 2 0 19102 65535 0][f 4 10 65535 0 0]What!?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Post-Festival MC]]
[s]Where'd that come from!?[n][f 1 3 65535][w][e]

[msg MSG_044_5_0 [Mishima]]
[s][bup 0 111 24 65535 0][vp 8 2 0 19102 65535 0][f 4 10 65535 0 0]Y-You...! Huh!?[n][f 1 3 65535][w][e]

[msg MSG_044_7_0 [Post-Festival MC]]
[s]Now this is drama! A boy caught[n]in the throes of bittersweet youth![n]A stunning confession of love![n][f 1 3 65535][w][e]
[s]And a rather interesting one at that![n][f 1 3 65535][w][e]

[msg MSG_044_9_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ヤジ)[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Post-Festival MC]]
[s]I think it was him![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Mishima]]
[s][bup 0 111 25 2 0][vp 8 2 0 19042 65535 0][f 4 10 65535 0 0]I-I...![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Post-Festival MC]]
[s]Sooo, Mishima-kun! What's your[n]relation to this guy?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Mishima]]
[s][bup 0 111 25 2 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I... Well...[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Post-Festival MC]]
[s]My, he's red as a beet![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Post-Festival MC]]
[s]But I'm a kind man. It hurts my heart[n]to bully this much![n][f 1 3 65535][w][e]
[s]Well, did you all enjoy our[n]drama-filled questioning? Thank you[n]very much, Mishima-kun![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ブーイング)[n][f 1 3 65535][w][e]

