[msg MSG_000_3_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ざわつく声)[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Post-Festival MC]]
[s]All right, that was a great performance[n]by the dance club![n][f 1 3 65535][w][e]
[s]Everybody give them another[n]round of applause![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7191 65535 0][f 4 10 65535 0 0]That sucked...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][f 4 10 65535 0 0]Sorry, dude. I was the one[n]that wanted to hang, but[n]I'm just bein' a bummer...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Akechi's dumb threats are[n]messin' with my head...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]We'll be okay, right...?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]We'll be fine.[e]
[s]It's looking bad...[e]
[s][f 0 8 2 1 2217]Let's not worry for now.[clr 27][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][coop 3 5 2]......[n][f 1 3 65535][w][e]
[s][bup 0 2 0 2 0][vp 8 2 0 7022 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100]Y-Yeah... If you say[n]so, then it gotta be true.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 2 0][vp 8 2 0 7085 65535 0][f 4 10 65535 0 0]Yeah...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 6 2 0][vp 8 2 0 7169 65535 0][f 4 10 65535 0 0][coop 3 10 2]...Okay. Thanks.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You always know the[n]right things to say.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Post-Festival MC]]
[s]And now, it's time for your[n]favorite Shujin tradition:[n]the Student Sharing Special![n][f 1 3 65535][w][e]
[s]Round of applause, everyone![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](パラパラとした拍手)[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]They're doin' this again...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]You'd think they woulda[n]gotten rid of it already.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Post-Festival MC]]
[s]All right, who has something to say?[n]Anyone, anyone!?[n][f 1 3 65535][w][e]
[s]No? I'll just have to pick someone then![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 0 2 0][vp 8 2 0 7060 65535 0][f 4 10 65535 0 0]Wanna head out?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]There are some booths[n]we haven't seen yet.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Post-Festival MC]]
[s]How about...[n][f 1 3 65535][w][e]
[s]The guy over there with the[n]bleached up hair![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 1][vp 8 2 0 7039 65535 0]F-For real!?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Post-Festival MC]]
[s]Well then, come on up![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 5 2 0][vp 8 2 0 7175 65535 0][f 4 10 65535 0 0]Dude, help me out here![n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]I can't do anything...[e]
[s]You can't ignore him.[e]
[s]Time for your big break.[e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7187 65535 0][f 4 10 65535 0 0]I-I know that![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7156 65535 0][f 4 10 65535 0 0]I know, dude! I just...[n]Why me!?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7041 65535 0][f 4 10 65535 0 0]This isn't what I meant[n]when I said I wanted to[n]be popular![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Post-Festival MC]]
[s]Now, now! You're not shy, are you!?[n][f 1 3 65535][w][e]
[s]Come, come. Everyone's waiting![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](拍手)[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Ugh... Fine![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Post-Festival MC]]
[s]And what is your name?[n][f 1 3 65535][w][e]

[msg MSG_027_7_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]R-Ryuji...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Post-Festival MC]]
[s]Ryuji!? You mean Ryuji Sakamoto!?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7022 65535 0][f 4 10 65535 0 0]Y-Yeah...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Post_Festival MC]]
[s]W-Well, now! Seems we've got an[n]interesting character here, folks![n][f 1 3 65535][w][e]
[s]Is there anything you would[n]like to tell us, Sakamato-kun?[n][f 1 3 65535][w][e]
[s]I am sure someone like you[n]would have quite a lot to say.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][vp 8 2 0 7079 65535 0][f 4 10 65535 0 0]W-Well... Um...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]I...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Post-Festival MC]]
[s]This is a shocker! The[n]rebellious Sakamato-kun has[n]a nasty case of stage fright![n][f 1 3 65535][w][e]
[s]Here, I'll give you a question...[n][f 1 3 65535][w][e]
[s]Do you think the Phantom Thieves[n]are really Shujin students?[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 1][vp 8 2 0 7041 65535 0][f 4 10 65535 0 0]E-Eh!?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](観衆のざわめき)[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Post-Festival MC]]
[s]We're all dying to know what[n]Akechi-kun was going to say about[n]their true identities.[n][f 1 3 65535][w][e]
[s]Some people theorize that they go[n]to our very school...[n][f 1 3 65535][w][e]
[s]So, are they from Shujin? What do you[n]think, Sakamato-kun?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Ryuji]]
[s][bup 0 2 4 2 0][vp 8 2 0 7194 65535 0][f 4 10 65535 0 0]Y-You see... Well...[n][f 1 3 65535][w][e]

[msg MND_038_5_0]
[s][vp 8 0 0 0 65535 0]Ryuji is in trouble...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I need to change[n]the subject...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 3 2 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0][f 4 10 65535 0 0]They...[n][f 1 3 65535][w][e]

[sel SEL_040_5_0 top]
[s]Are you dating someone!?[e]
[s]Your stuttering's cute![e]
[s]I've always loved you![e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 24 2 0][vp 8 2 0 7189 65535 0][f 4 10 65535 0 0]Huh...!? A what!?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Post-Festival MC]]
[s]It seems we have a question[n]from the crowd![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ryuji]]
[s][bup 0 2 24 2 0][vp 8 2 0 7029 65535 0][f 4 10 65535 0 0]Eh...!?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Post-Festival MC]]
[s]Where'd that come from!?[n][f 1 3 65535][w][e]

[msg MSG_044_5_0 [Ryuji]]
[s][bup 0 2 24 2 0][vp 8 2 0 7039 65535 0][f 4 10 65535 0 0]F-For real...!?[n][f 1 3 65535][w][e]

[msg MSG_044_7_0 [Post-Festival MC]]
[s]Now this is drama! A boy caught[n]in the throes of bittersweet youth![n]A stunning confession of love![n][f 1 3 65535][w][e]
[s]And a rather interesting one at that![n][f 1 3 65535][w][e]

[msg MSG_044_9_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ヤジ)[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Post-Festival MC]]
[s]I think it was him![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 22 2 0][vp 8 2 0 7047 65535 0][f 4 10 65535 0 0]D-Dude...![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Post-Festival MC]]
[s]Sooo, Sakamoto-kun! What's your[n]relation to this guy?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Ryuji]]
[s][bup 0 2 24 2 0][vp 8 2 0 7038 65535 0][f 4 10 65535 0 0]M-My what!?[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Post-Festival MC]]
[s]My, he's red as a beet![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Post-Festival MC]]
[s]But I'm a kind man. It hurts my heart[n]to bully this much![n][f 1 3 65535][w][e]
[s]Well, did you all enjoy our[n]drama-filled questioning? Thank you[n]very much, Sakamoto-kun![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [(SE)秀尽学園生徒]]
[s][vp 8 0 0 0 65535 0](ブーイング)[n][f 1 3 65535][w][e]

