[msg MND_000_0_1]
[s][vp 8 0 0 0 65535 0]Ryuji and I roamed the[n]snowy Shibuya streets[n]for quite some time...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7047 65535 0]Damnit. There is way too[n]many people out right now.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I could barely hear myself[n]think in the crowds![n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7191 65535 0]There were so many couples, too...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is kinda bizzare how they[n]are so open like that.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Do you envy them?[e]
[s]Do you want to do that?[e]
[s][f 0 8 2 1 2217]You're all I was looking at.[clr 27][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0][coop 15 10 2]No? Kinda? I dunno, honestly.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eh, who knows. Whatever.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7041 65535 0][coop 15 5 2]Huh!?[n][f 1 3 65535][w][e]
[s][bup 0 2 23 4 0][f 4 24 0 4 6 38 5 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't just ask me that[n]outta no where, man![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][vp 8 2 0 7189 65535 0][coop 15 15 2]W-What the hell, man!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The hell am I even supposed[n]to say to that!?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, now that we're here,[n]whatcha wanna do now?[n]Just hang?[n][f 1 3 65535][w][e]

[sel SEL_005_1_0 top]
[s][f 0 8 2 1 2217]Let's just relax.[clr 27][e]
[s][f 0 8 2 1 2217]Let's have some fun.[clr 27][e]
[s]Merry Christmas.[e]

[msg MSG_005_3_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0][coop 15 15 2]That'd be nice after so long[n]of runnin' around everywhere![n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0][coop 15 15 2]Sure, dude! Whatcha thinkin'?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We could play some games?[n]There's one I've been dyin'[n]to play![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7071 65535 0][coop 15 10 2]Oh, right! Merry Christmas![n][f 1 3 65535][w][e]

[msg MND_011_5_0]
[s][vp 8 0 0 0 65535 0]I won't be able to see Ryuji[n]again after tomorrow...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We spent a long time talking...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]By the way, here, dude.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I thought you might like it.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Thank you.[clr 27][e]
[s][f 0 8 2 1 2217]I'll cherish it.[clr 27][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0][coop 15 15 5]Hope ya like it, man! Wanted to get ya more,[n] but I couldn't.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 3 4 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7085 65535 0]So... uh... ya mind if I ask[n]ya somethin' more serious?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You okay, man?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A lot's happened. We didn't[n]have time to talk about it.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]And... I can't scratch the feelin'[n]that somethin' is wrong.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The way you've been actin'...[n]I don't know. Something's off.[n][f 1 3 65535][w][e]

[msg MSG_999_0_0 [Sae]]
[s]If that happens, there's no telling what[n]they'll do to you or your teammates.[n][f 1 3 65535][w][e]
[s]There's even the possibility that they'll[n]fabricate a crime and move to arrest[n]you all.[n][f 1 3 65535][w][e]

[msg MND_999_1_0]
[s][vp 1 0 0 0 0 0]I have to turn myself in to[n]make sure Ryuji stays safe...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But telling him about it would[n]only cause him to panic...[n][f 1 3 65535][w][e]

[msg MSG_013_1_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What's wrong, man?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's nothing.[e]
[s]I'm sorry.[e]

[msg MSG_014_1_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]Oh...[n][f 1 3 65535][w][e]

[msg MSG_014_3_0 [Ryuji]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 2 3 300 1][vp 8 2 0 7194 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7156 65535 0]This is somethin' ya can't[n]even tell me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Can't we tell each other[n]anythin', man?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sorry, man. Didn't mean to[n]bring the room down.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I think it's 'bout time for me[n]to leave, yeah?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]I'll walk you back.[e]
[s]Be careful.[e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7036 65535 0]No, no need.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Yeah... I will, don't worry.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7173 65535 0]Listen, dude... I don't know[n]what's happenin'... but don't[n]do anythin' big.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya tend to jump into things...[n]I don't want to see ya[n]hurt again.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, just... be careful, okay...?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]See ya...[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]I made Ryuji worry...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Even so, this is the only way...[n][f 1 3 65535][w][e]

