[msg MND_000_0_1]
[s][vp 8 0 0 0 65535 0]Mishima and I roamed the[n]snowy Shibuya streets[n]for quite some time...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19028 65535 0]There was quite a lot of people[n]out wandering about tonight.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We weren't even able to get[n]something to eat due to all[n]of the people...[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19066 65535 0]I'm sorry. I should have thought[n]of something beforehand to eat.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]We can still eat here.[e]
[s]I am quite hungry...[e]
[s][f 0 8 2 1 2217]You're enough for me.[clr 27][e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19067 65535 0][coop 15 10 111]Oh, yeah! We could![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I don't think I've ever eaten[n]anything from your cafe before.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19102 65535 0][coop 15 5 111]I'm sorry![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][bup 0 111 24 4 0][vp 8 2 0 19040 65535 0][coop 15 15 111]E-Eh!? Huh!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I... Um... I-I feel the same...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S-So... what do you usually[n]do here...?[n][f 1 3 65535][w][e]

[sel SEL_005_1_0 top]
[s][f 0 8 2 1 2217]I make tools.[clr 27][e]
[s][f 0 8 2 1 2217]Usually movies or games.[clr 27][e]
[s]Just sleep...[e]

[msg MSG_005_3_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 15 15 111]Tools!? You mean for the Phantom Theives!?[n][f 1 3 65535][w][e]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 4 100][vp 8 2 0 19024 65535 0]That's so cool! Is it with that[n]desk over there? Can I see!?[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 15 15 5]Oh, what games? I haven't played[n]many games before.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19112 65535 0]I've... also been too busy with[n]the forum to watch anything... Haha...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19046 65535 0][coop 15 10 5]Just... sleep...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Come on! Stop messing with me![n]You gotta do more than that![n][f 1 3 65535][w][e]

[msg MND_011_5_0]
[s][vp 8 0 0 0 65535 0]I won't be able to see Mishima[n]again after tomorrow...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We spent a long time talking...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19071 65535 0]A-Also, I got you something![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]U-Um... I hope you like it, [fName]![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Thank you.[clr 27][e]
[s][f 0 8 2 1 2217]I'll cherish it.[clr 27][e]

[msg MSG_009_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0][coop 15 15 5]So you like it? I'm glad![n]I was hoping you would![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Mishima]]
[s][bup 0 111 3 4 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19104 65535 0]S-So... Um... [fName]...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How are you feeling?[n]Y-You know... after what happened[n]with the police?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]When I saw the news that you[n]were arrested and... yeah...[n]I couldn't even think.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19018 65535 0]S-So... I just want to make sure[n]everything is okay.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I don't know what exactly happened,[n]and I know it's thief business...[n]but I am worried for you.[n][f 1 3 65535][w][e]

[msg MSG_999_0_0 [Sae]]
[s]If that happens, there's no telling what[n]they'll do to you or your teammates.[n][f 1 3 65535][w][e]
[s]There's even the possibility that they'll[n]fabricate a crime and move to arrest[n]you all.[n][f 1 3 65535][w][e]

[msg MND_999_1_0]
[s][vp 1 0 0 0 0 0]I have to turn myself in to[n]make sure Mishima stays safe...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But telling him about it would[n]only cause him to panic...[n][f 1 3 65535][w][e]

[msg MSG_013_1_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're... okay, right?[n]Everything is fine now, right?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's nothing.[e]
[s]I'm sorry.[e]

[msg MSG_014_1_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Why...?[n][f 1 3 65535][w][e]

[msg MSG_014_3_0 [Mishima]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 111 3 300 1][vp 8 2 0 19082 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19032 65535 0]I'm sorry... It isn't my place to ask.[n]I'm not part of all of that.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Mishima]]
[s][bup 0 111 3 4 0].......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm... going to go home.[n]It's getting late.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]I'll walk you back.[e]
[s]Be careful.[e]

[msg MSG_018_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19066 65535 0]I'm sorry...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19027 65535 0]I'll be fine.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19104 65535 0]Whatever it is... just... please be safe.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I know what you do is dangerous, but...[n]I couldn't go on if you were hurt...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19129 65535 0]Goodbye...[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]I made Mishima worry...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Even so, this is the only way...[n][f 1 3 65535][w][e]

