[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, right, today's Valentine's Day.[n]No wonder there were so many guys[n]bringing girls in here.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't you have anything exciting[n]happening? I mean, you've been here[n]nearly a whole year.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Y'know, when I was young, hoo boy...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Yo. What's up?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wha- Ryuji?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you two just hanging out? Or...?[n][f 1 3 65535][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Well, doesn't matter.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll leave the store to you for tonight.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enjoy yourselves.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]Hope the boss wasn't too confused...[n]He didn't seem to know what[n]to say about me coming over.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]How ya doin' dude? It's been a while.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Happy now that you're here.[e]
[s]It's been a lot.[e]
[s]Glad to be back.[e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7041 65535 0][coop 3 10 2]H-How can you say that stuff[n]so easily...!?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0][coop 3 5 2]Yeah... I bet it has been for ya.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0][coop 3 5 2]Same here, dude! Was weird not[n]havin' ya around.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]Anyway, I wanted to give ya this.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What do I say here...?[n]Happy... Valentine's Day...?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]You got me chocolate?[clr 27][e]
[s]So I'm your valentine?[e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 20 4 0][f 4 10 65535 0 0][vp 8 2 0 7183 65535 0][coop 3 15 2]Well, yeah! I mean... we're... um...[n]Y-Yeah, I did.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7029 65535 0][coop 3 5 2]Do you have to say it so bluntly!?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I just wanted to give ya[n]somethin' for today.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Should I have not?[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s][f 0 8 2 1 2217]It makes me happy.[clr 27][e]
[s]I'm glad.[e]
[s]I appreciate it.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0][coop 3 15 2]Okay... That's good, then. I don't[n]know how to do this shit.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]I'm glad I thought to get ya[n]somethin', then.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Cool! Glad I gotcha somethin', then![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]By the way, I've been keepin'[n]tabs on the track team and all.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Apparently, everythin' there is fully[n]figured out.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7071 65535 0]I was thinkin' of doin' some[n]running of my own. Gettin' back[n]into it, ya know?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s][f 0 8 2 1 2217]You want to train more together?[clr 27][e]
[s]Weren't you already doing that?[e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0][coop 3 5 2]Hell yeah, dude! Of course I do![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Well, yeah, but I wanna get[n]some new shoes maybe to really[n]get it runnin', ya know?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 0 4 0]......[n][f 1 3 65535][w][e]
[s][bup 0 2 20 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Can I... maybe come over there?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So... I've been thinkin'...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]You're headin' home next month, right?[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s][f 0 8 2 1 2217]Will you miss me?[clr 27][e]
[s]I am.[e]
[s]Want to come with me?[e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 23 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0][coop 3 15 2]I... Um... Y-Yeah, I will.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7191 65535 0]I was hopin' I got the time wrong.[n]It really has been a year...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7189 65535 0][coop 3 10 2]Huh!? I-I don't think that's[n]possible, dude![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wait, why am I answerin' that seriously!?[n]You know that isn't possible![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]I... still don't really understand[n]all of this stuff fully yet.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was kinda worried when I remembered[n]you'd have to leave soon... But[n]I'm not so worried now.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 4 0][f 4 24 0 6 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm... just glad that nothin'[n]will seem to change.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Ryuji]]
[s][bup 0 2 20 4 0][f 4 10 65535 0 0][vp 8 2 0 7173 65535 0]And on that note... I kinda[n]wanted to stay for a bit,[n]if that is cool...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I just... wanna spend as[n]much time with ya as possible...[n]Ya know...?[n][f 1 3 65535][w][e]

[msg MND_100_0_0]
[s][vp 8 0 0 0 65535 0]I spent a romantic evening[n]with Ryuji...[n][f 1 3 65535][w][e]

