[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, right, today's Valentine's Day.[n]No wonder there were so many guys[n]bringing girls in here.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't you have anything exciting[n]happening? I mean, you've been here[n]nearly a whole year.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Y'know, when I was young, hoo boy...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ah, Sojiro. Good afternoon.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're... Yusuke, right?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I didn't think that you were...[n]Well, it doesn't matter. Picked a rather[n]eccentric one, though.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll leave the store to you for tonight.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Enjoy yourselves.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4080 65535 0]The atmosphere of this cafe is[n]as calming as ever... It puts[n]my mind at ease.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]I thank you for spending this time[n]with me, [fName].[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Relax all you like.[e]
[s]What should we do today?[e]
[s]How've you been?[e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 3 10 5]I shall. It is hard to not in[n]such a place.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][coop 3 5 5]There are quite a few things which we could do.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Perhaps we could read some novels?[n]Or maybe paint some? Do you not[n]also have a television?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0][coop 3 5 5]I have been well, even with[n]all of chaos happening recently.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]It is Valentine's day, and so I[n]wish to give you this.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do hope you like what[n]I have done with it.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]You've sculpted it...[clr 27][e]
[s]It's art.[e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0][coop 3 15 5]Indeed. I believe some symbolism[n]is needed in times such as these.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0][coop 3 5 5]It was too bland before. It[n]needed a special touch worthy[n]of the occasion.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0]I am glad I could hand this to you[n]on this day.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]This is the first time I have ever[n]given such a thing. I wanted[n]to make sure it was special.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s][f 0 8 2 1 2217]It is definitely special...[clr 27][e]
[s]It makes me happy.[e]
[s]I don't even want to eat it...[e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0][coop 3 15 5]This means I have done my[n]duty as an artist! Nothing makes[n]me happier to hear.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Splendid. I am glad you like[n]my chocolate.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]What meaning would there be[n]if you didn't?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There's no need to worry. I can[n]just make another for display[n]purposes.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4150 65535 0]I have been thinking quite a lot[n]on the next art piece I intend[n]to make.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I still do not know what the[n]theme will be, but I have high[n]hopes for it.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]I believe that with you beside[n]me, I can turn any prompt into[n]the beauty it deserves.[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s][f 0 8 2 1 2217]I'm looking forward to it.[clr 27][e]
[s]So no more naked paintings?[e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4031 65535 0][coop 3 5 5]With your encourangement, I no[n]doubt will be able to paint[n]to my heart's content.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]I wasn't thinking of it, but I will[n]not turn it down with the right model.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]May I sit next to you, [fName]?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There is something still lingering on my mind.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4027 65535 0]You are heading back to your[n]hometown next month; is that right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do not know how long distance[n]works for these sorts of relationships...[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s][f 0 8 2 1 2217]Nothing will change.[clr 27][e]
[s]We can make it work.[e]
[s]You could come with me.[e]

[msg MSG_034_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4088 65535 0][coop 3 15 5]Yes. I do believe it will be fine.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Knowing you, I am sure it[n]will be just fine.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yusuke]]
[s][bup 0 5 24 4 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0][coop 3 10 5]I... do not believe that is a[n]possibility, unfortunately.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]There was quite a lot which was spiraling[n]through my mind before coming here...[n][f 1 3 65535][w][e]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, now that I am here, all[n]of that noise vanished into thin air.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Your presence always does this to me.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Right now all I care about...[n]is being with you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It has been far too long since[n]we could be together, after all.[n][f 1 3 65535][w][e]

[msg MND_100_0_0]
[s][vp 8 0 0 0 65535 0]I spent a romantic evening[n]with Yusuke...[n][f 1 3 65535][w][e]

