[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]Ah, [fName]. You've finally arrived.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was worried you had gotten[n]carried away in the crowd.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Were you waiting long?[e]
[s]I'm not Futaba.[e]
[s]Merry Christmas.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Do not fret. I, myself, have only[n]arrived moments before you.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]That is true. You are not.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]Merry Christmas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It feels rather strange to[n]be in this moment after what[n]happened only a little bit ago.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]I was thinking we could go[n]get something to eat, just[n]the two of us.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is evening, after all.[n]I am sure we are both starved[n]after earlier as well.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Of course, I have no money.[n]You wouldn't mind paying,[n]would you?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Excellent. Let us head off.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Hm? Is something the matter, [fName]?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Why don't we hold hands?[e]
[s]You know, my hand is rather cold.[e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh. I see. I do recall that[n]being something couples do on[n]these occassions.[n][f 1 3 65535][w][e]
[s][bup 0 5 20 4 0][f 4 24 0 4 6 35 3 100][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]Very well. New experiences can[n]broaden the palette.[n]I shall accept.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Do you need to go inside?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wait, are you asking to... hold hands?[n][f 1 3 65535][w][e]
[s][bup 0 5 21 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Why not say so earlier? I accept.[n][f 1 3 65535][w][e]

