[msg MSG_000_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19083 65535 0]This was totally worth it![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I haven't had cake this[n]good before![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Glad it worked out in the end.[e]
[s]It's been nice being with you.[e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19020 65535 0]I'm glad I could make this[n]worth it for you, too![n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 5 0]Mishima is staring at me...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I wonder when that got[n]on your nose.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19112 65535 0]To think I'd see you of all[n]people doing things like that. Haha.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I... honestly don't feel like[n]I deserve it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19027 65535 0]I mean... you're so cool! It feels strange[n]that of all people... you chose[n]me to spend time with.[n][f 1 3 65535][w][e]
[s][bup 0 111 21 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That just means I appreciate it[n]all the more when we're together![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So... thank you, [fName]![n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Why thank me?[e]
[s]I didn't do anything.[e]

[msg MSG_008_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19038 65535 0]How could you even ask that?[n]There's so much to thank![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You've helped so many people[n]including me![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You even helped me realize I'm[n]not some zero with no meaning.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So... thank you![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0]With all that you have done,[n]you saying that proves how you[n]deserve it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You've done so much, [fName]! I look up to you![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 2 0 19071 65535 0]Oh! I actually got something[n]for you![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I wanted to get you[n]something for Christmas![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19055 65535 0]I hope you like it![n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I... hope that we can be[n]like this for much longer.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I always get excited to spend[n]more time with you.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0]Hm? Oh, look![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I didn't think it would be[n]snowing anytime today.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19082 65535 0]It looks almost like a dream.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]It'll be hard to get home.[e]
[s]It's real life.[e]

[msg MSG_021_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It will be hard, yeah...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But I shouldn't stay here too[n]long...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19130 65535 0]U-Unless you want me to, th-that is...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Mishima]]
[s][bup 0 111 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I hope so. I wouldn't want[n]any of this to be a dream.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Mishima]]
[s][bup 0 111 20 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The times I spend with you[n]are the best times I've had.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I would not spend my time[n]any differently than this...[n]with you.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19018 65535 0]So... perhaps maybe I can[n]stay a little longer?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I want to be with you... and a[n]bit closer, if you don't mind.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 4 0]Mishima and I spent some[n]time alone together...[n][f 1 3 65535][w][e]

