[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7040 65535 0]Holy crap... This is amazin'![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]This makes everything totally worth it![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Glad it worked out in the end.[e]
[s]It's been nice being with you.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 20 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Oh. Um... Y-Yeah. Same here.[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji is staring at me...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]It was on your nose.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]How'd ya even manage that?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 20 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]Ya know... the more we hang out...[n]or... I guess date, the more[n]natural it feels.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was honestly pretty nervous[n]on this at first, but now?[n]Not so much.[n][f 1 3 65535][w][e]
[s][bup 0 2 21 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya really do know how to[n]make others feel better.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya helped me quite a lot as well[n]for the short time you've been here...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So... um... I guess I'm tryin' to[n]say 'thank you'.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Why thank me?[e]
[s]I didn't do anything.[e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Dude, because ya rock, man![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If it wasn't for you I'd[n]probably still be dealin'[n]with that asshole Kamoshida.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'd also still be dealin' with[n]bein' some outcast with no[n]place of my own.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That's why I'm thankin' ya![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7156 65535 0]Ya serious, dude?[n]You've done more than enough![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Not just for me, but for[n]plenty of others as well![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]Speakin' of which, I gotcha somethin'![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's... as a thank you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You helped me out a lot. I just[n]wanted to show ya I appreciate it.[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I... wouldn't trade my time[n]with ya for anythin'...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7079 65535 0]U-Um...! Well, a-anyway, movin' on![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]L-Look out there![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7029 65535 0]Man, it's goin' down hard, huh?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's kinda nice lookin'.[n]Doesn't look real.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]It'll be hard to get home.[e]
[s]It's real life.[e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yeah, it will be.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]I can't just stay here, though.[n]That seems a bit awkward,[n]right?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I can just wait a little bit.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Yeah... It is.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7173 65535 0]Times like these make everything[n]that has happened worth it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There are times where I[n]swear I'm going to wake up[n]and be back to how it was before.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But I don't, and I continue seein'[n]you everyday.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, don't go disappearin' on me, yeah?[n]Stay with me.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]And... perhaps we can go just[n]a little faster...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I kinda wanna be a little[n]closer... just for right now.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji and I spent some[n]time alone together...[n][f 1 3 65535][w][e]

