[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]This cake... it is superb![n]Indeed, this was worth our efforts.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Glad it worked out in the end.[e]
[s]It's been nice being with you.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]I share the same sentiment.[n][f 1 3 65535][w][e]
[s][bup 0 5 4 4 0][f 4 24 0 4 6 34 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...?[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke is staring at me...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You had some of it on[n]your nose.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]I do wonder how it managed[n]to end up there.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It looked almost like paint,[n]in a way.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]This could be due to my love[n]of art, though I do wonder[n]how a portrait of you would look.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]With how picturesque you are,[n]it would make for a marvelous piece.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It would be more personal[n]than the ones I have created[n]thus far.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0]Perhaps it could be a thank you...[n]for everything you have done.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Why thank me?[e]
[s]I didn't do anything.[e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is from you I found my[n]place in the world and could[n]move forward.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Without you, I would not[n]be here right now.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]So... truly, thank you.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The fact that you believe[n]such a thing is enough reason[n]for you to be thanked.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Not many would face the risk of[n]death to save others. I am one[n]amongst the many you have saved.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That is exactly the reason I[n]offer you this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I made it myself,[n]for you to have with you.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]I thank you, [fName].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You not only freed me from the[n]chains of despair, you allowed me to be[n]my true self. Therefore, I thank you.[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have never been happier[n]than when I am with you.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]I apologize for getting[n]so incredibly serious. I truly[n]cannot help myself.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Oh.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The snowfall is immensely beautiful[n]on nights such as this, is it not?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is as if it was a painting.[n]The dark sky, white snow, lights[n]of the city. Magnificent.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]It'll be hard to get home.[e]
[s]It's real life.[e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]It shall.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Do not fret. I have dealt[n]with snow such as this before.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I may need to stay longer[n]to wait for it to lighten, however.[n]I hope you do not mind.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]I truly hope so.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In the past, I believed evenings[n]and sights like this to be only in paintings.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]I have been proven horribly[n]wrong since being with you.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]In these occasions, being[n]wrong is not the worst thing[n]in the world.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][bup 0 5 20 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]If anything, I wish for you to[n]prove me wrong more. To show me[n]more of the sights which I was blind to.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]I also... wish for you to give[n]me more experiences which[n]I didn't have prior.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So, if you do not mind...[n]I would like to be closer.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke and I spent some[n]time alone together...[n][f 1 3 65535][w][e]

