[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, right, today's Valentine's Day.[n]No wonder there were so many guys[n]bringing girls in here.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't you have anything exciting[n]happening? I mean, you've been here[n]nearly a whole year.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y'know, when I was young, hoo boy...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Yo. What's up?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wha- Ryuji?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you two just hanging out? Or...?[n][f 1 3 65535][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Well, doesn't matter.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll leave the store to you for tonight.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Enjoy yourselves.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Boss seemed confused... Guess it makes sense.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Take a seat.[e]
[s]I'll get you some soda.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Thanks, bro. Was feelin' a bit thirsty.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 3 5 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]How ya been, bro? We haven't been able[n]to talk much at all.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]I've been okay.[e]
[s]Just glad to be home.[e]
[s]How about you?[e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya sure, dude? You've been through[n]a lot... bein' in jail and all...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We're both happy 'bout that.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 3 5 0]......[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 3 5 0][f 4 10 65535 0 0][vp 8 2 0 7191 65535 0]You really scared me there when[n]ya disappeared, dude...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You were there one second and gone[n]the next. It was like a bad dream.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I still have a hard time wrapping[n]my head around everything...[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Sorry.[e]
[s]It's my bad.[e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 0 5 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's not like ya meant for it...[n]It all happened way too suddenly.[n][f 1 3 65535][w][e]
[s][bup 0 2 3 5 0][f 4 24 0 4 6 38 12 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But... ya seriously need to be careful![n]Stop jumpin' into things and not[n]tellin' me 'bout it![n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Ryuji]]
[s][bup 0 2 1 5 0][f 4 10 65535 0 0][vp 8 2 0 7071 65535 0]Anyway... I gotcha somethin'.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 1 5 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]It's Valentine's Day and all...[n]So here ya go.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]This makes me happy.[e]
[s]I didn't expect this.[e]
[s]I'm your Valentine?[e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 1 5 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]I was hopin' you'd like them.[n]They ain't much, but it's somethin'.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 1 5 0][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0]Seriously, dude? I asked ya to hang[n]on Valentine's Day for a reason.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 24 5 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]I... u-um... I guess, yeah...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 20 5 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]It's so weird... It still feels like[n]we're in some sorta dream reality.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I honestly can't tell the difference[n]anymore. We're in the real world, right?[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]We are.[e]
[s]It's the real world.[e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]Okay... That's good.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I want this to be real.[n][f 1 3 65535][w][e]
[s][bup 0 2 3 5 0][f 4 24 0 4 6 38 12 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well... I guess some things[n]I wish weren't...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 3 5 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Can I sit next to ya?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]So... you're goin' home next month...[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]I am.[e]
[s]Will you miss me?[e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 3 5 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]Yeah...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 23 5 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]...Yeah. I will.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 0 5 0][f 4 10 65535 0 0][vp 8 2 0 7191 65535 0]I'm so used to you bein' around.[n]It'll be hard with ya gone and all.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're the one that gave me a place to be...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 1 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We can hang and be together[n]still, though.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 21 5 0][f 4 10 65535 0 0][vp 8 2 0 7173 65535 0]After all, someone I know never[n]backed down when they were facin' shit.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]They've inspired me to go for what[n]I want and believe in as well.[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]Who?[e]
[s]Are you talking about...[e]

[msg MSG_035_0_0 [Ryuji]]
[s][bup 0 2 21 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A very cool bro, that's who.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ryuji]]
[s][bup 0 2 21 5 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]And... the guy I care for most.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So don't ya go leavin' me[n]too soon, yeah?[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]I spent a romantic evening[n]with Ryuji...[n][f 1 3 65535][w][e]

