[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, right, today's Valentine's Day.[n]No wonder there were so many guys[n]bringing girls in here.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Don't you have anything exciting[n]happening? I mean, you've been here[n]nearly a whole year.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y'know, when I was young, hoo boy...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4006 65535 0]Ah, Sojiro. Good afternoon.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're... Yusuke, right?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I didn't think that you were...[n]Well, it doesn't matter. Picked a rather[n]eccentric one, though.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll leave the store to you for tonight.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Enjoy yourselves.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Greetings, [fName]. I'm glad you were[n]able to be with me today.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Have a seat.[e]
[s]I'll make you some coffee.[e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4179 65535 0]I appreciate it. Thank you.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Relaxing like this after so long of chaos...[n]It feels almost foreign.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]A lot happened to us.[e]
[s]At least it's finally over.[e]
[s]Make sure to take care of yourself.[e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]Much more than "a lot"... and mostly[n]to you, to my distain.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]Indeed. I am glad. I got so tense I could[n]barely move my brush.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 2 0 4028 65535 0]Should I not be the one saying that[n]to you? You were the one behind metal[n]bars, after all.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]When I heard you had turned yourself in,[n]it was like time had stopped.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]For once... there was no color around me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]I know it was for a good cause...[n]but it was rather horrifying to[n]hear such news...[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Sorry.[e]
[s]My bad.[e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4139 65535 0]There is no need to apologize. I would[n]have very well done the same[n]if I were you.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, I would much appreciate if we[n]avoid these situations entirely.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If there is something you must do,[n]I will do it with you. We shall go down[n]together, if at all.[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 2 0 4080 65535 0]Well, that's besides the point. It is[n]Valentine's Day, so I wish to give you this.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]I ended up taking some... artistic liberties[n]on the chocolate itself.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4037 65535 0]I hope you do not mind.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]This looks amazing.[e]
[s]I didn't expect this.[e]
[s]Does this mean you're the girl here?[e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]I made sure to shape it like my mask.[n]Symbolism is important in these matters.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]I hope it is a welcome surprise, then.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Is that important? Would you like me to be?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]You know... I have been thinking about my[n]next piece recently.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Our experiences as of late have been guiding[n]my mind. I am thinking of challenging myself.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]It'll be an incredible one, I'm sure.[e]
[s]I'm rooting for you.[e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 21 5 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]Your encouragement sets my motivation ablaze.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I don't have a theme yet, but thinking[n]of it allowed my mind to not worry[n]about you in prision.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][bup 0 5 3 5 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4027 65535 0]May I... sit next to you, [fName]?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]If I recall, you are going back home[n]next month, correct?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]I will.[e]
[s]Will you miss me?[e]

[msg MSG_029_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 2 0 4064 65535 0]...I see.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 23 5 0][f 4 10 65535 0 0][vp 8 2 0 4022 65535 0]I will... deeply.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You being gone in prision was struggle enough...[n]Though, I guess it isn't exactly alike.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]It will be a challenge to have a[n]relationship long-distance...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]Though, challenge helps make way to[n]greater outcomes in the end.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It will work out.[n]I am not worried in the slightest.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yusuke]]
[s][bup 0 5 1 5 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]A certain person showed me struggle is not[n]something to shy away from.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Through that darkness, they became my[n]rays of hope to guide me through the dark.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]With them here... I will not be discouraged.[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]Who?[e]
[s]Are you talking about...[e]

[msg MSG_035_0_0 [Yusuke]]
[s][bup 0 5 21 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I hope that he will not be discouraged[n]as well. I am strongest when he is smiling.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yusuke]]
[s][bup 0 5 21 5 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]Why don't we spend some time closer[n]together...? For just a bit longer...[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]I spent a romantic evening[n]with Yusuke...[n][f 1 3 65535][w][e]

