[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]I met up with Yusuke at the[n]aquarium...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]I knew that an aquarium like this existed,[n]but to think it was so beautiful.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]Just looking at the design of the halls...[n]the placement! It is truly energizing![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]I should bring my canvas here one day.[n]Such material would lead to astounding results.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]I'll join you.[e]
[s]We can come here anytime.[e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]In that case, what about tomorrow?[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah... No. That seems too soon.[n]I'm sure you'd have plans already.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]Is this... for White Day?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]It is[e]
[s]That's correct.[e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4179 65535 0]I didn't expect you to have[n]something like this planned.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You are certainly full of surprises, [fName].[n]I honestly never know what it is you are thinking.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But... that isn't necessarily a bad thing.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Is this supposed to be a date...?[n]For White Day?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]It is.[e]
[s]That's correct.[e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]Excellent! When I did not see you on[n]Valentine's Day, I got a tad restless.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I was wondering if perhaps...[n][f 1 3 65535][w][e]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 1 300 1][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]Well, it does not matter.[n]We can enjoy our time together now.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4027 65535 0]This... date... It's meant to be for[n]White Day, correct?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Is it supposed to be an apology[n]for what happened before?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Of course.[e]
[s]Yes.[e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 2 0 4064 65535 0]...I see.[n][f 1 3 65535][w][e]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]When it all happened, I was left in a[n]state of shock. I could hardly believe[n]what had occurred.[n][f 1 3 65535][w][e]
[s][f 4 5 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seeing your efforts to repair that[n]mistake of yours eases my mind a bit.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]...Yusuke seems pleased.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4080 65535 0]Well, anyway, I believe we have stayed[n]here for long enough.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Naturally, I could stay and look at[n]this beauty forever. However, I am sure[n]you wouldn't enjoy watching for hours.[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]I have a reservation set.[e]
[s]I have a place we can go eat.[e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]You do!? Truly!?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4052 65535 0]Let us go, then![n][f 1 3 65535][w][e]

