[msg MSG_000_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19040 65535 0]This... This is such a nice place...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You actually reserved this for us?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]I did.[e]
[s]It was recommended to me.[e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19044 65535 0]It must have been so much[n]work to get a place like this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's so nice. I feel out of[n]place in such a nice resturant.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0]They much be pretty important[n]to have ties to such a place.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Though, it makes sense you'd[n]know someone like that.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19110 65535 0]You look so composed, too.[n]It's like you fit right in.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're... seriously so cool, [fName].[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]You're making me blush.[e]
[s]Thank you.[e]

[msg MSG_006_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0]It's the truth. You're... just[n]so amazing.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I don't know how I ended up[n]being with someone as amazing as you.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Mishima]]
[s][bup 0 111 23 4 0][f 4 10 65535 0 0][vp 8 2 0 19067 65535 0]U-Um... I need to go for a second![n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]When should I give him the gift?[n][f 1 3 65535][w][e]

[msg MND_011_0_0]
[s][vp 8 0 0 0 65535 0]○○○ is calling me...[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]I can't answer this now...![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 2 0 19032 65535 0]Sorry for suddenly leaving like that.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Didn't you get a call just now?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's not a big deal.[e]
[s]Don't worry about it.[e]

[msg MSG_015_0_0 [Mishima]]
[s][bup 0 111 3 4 0][f 4 10 65535 0 0][vp 8 2 0 19130 65535 0]Oh... All right.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 2 0 19032 65535 0]Sorry about suddenly leaving like that.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Announcer]]
[s][vp 8 0 0 0 65535 0]Ladies and gentlemen, thank you for[n]joining us on this special day.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We wish you all an unforgettable[n]evening, with one last finishing touch[n]from us...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0]Is something happening?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][bup 0 111 4 4 0][f 4 10 65535 0 0][vp 8 2 0 19067 65535 0]It's... so pretty...[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]I have a gift for you.[e]
[s]I want you to have this.[e]

[msg MSG_021_0_0 [Mishima]]
[s][bup 0 111 24 4 0][f 4 10 65535 0 0][vp 8 2 0 19040 65535 0]What is... This is for me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]They're... amazing. Thank you, [fName].[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Mishima]]
[s][bup 0 111 20 4 0][f 4 10 65535 0 0][vp 8 2 0 19044 65535 0]I... don't even know what to say...[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]Do you like it?[e]
[s]You don't need to say anything.[e]
[s]All of it's for you.[e]

[msg MSG_024_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19022 65535 0]I... love it, [fName].[n]It's.. more than I could have[n]hoped for![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 2 0 19018 65535 0]The least I can do is thank you, though.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Mishima]]
[s][bup 0 111 24 4 0][f 4 10 65535 0 0][vp 8 2 0 19044 65535 0]It's so much, though.[n]Too much![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Mishima]]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I don't even know how to react.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Mishima]]
[s][bup 0 111 0 4 0][f 4 10 65535 0 0][vp 8 2 0 19082 65535 0]Even with this, you know exactly[n]what to do.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're so cool... I can't believe[n]I get to experience this with you.[n][f 1 3 65535][w][e]
[s][bup 0 111 1 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I never would have guessed[n]when I first met you that you'd[n]be so... just you.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Thanks.[e]
[s]You're making me blush.[e]

[msg MSG_030_0_0 [Mishima]]
[s][bup 0 111 20 4 0][f 4 10 65535 0 0][vp 8 2 0 19018 65535 0]I... have a lot of time on[n]my hands after this, you know.[n][f 1 3 65535][w][e]
[s][bup 0 111 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I can stay with you longer...[n]If that's okay with you.[n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Mishima and I spent some[n]time alone together...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Once it got late, I walked him[n]back to the station...[n][f 1 3 65535][w][e]

