[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 2 0 7189 65535 0]What... the heck is this!?[n]Ya got this for us?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]I did.[e]
[s]It was recommended to me.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0]How the hell!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wasn't it a lotta work to get[n]a place like this? It's White Day,[n]after all...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 2 0 7115 65535 0]Recommended? By who?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I knew ya had connections,[n]but not to this extent.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 2 0 7079 65535 0]Even the food here is fancy as hell.[n]I can't even pronounce some of[n]these names.[n][f 1 3 65535][w][e]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gettin' somethin' like this for me...[n]Thank you.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Of course I would.[e]
[s]It's worth it for you.[e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Y-You really know how to get[n]someone flustered, don't ya?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 23 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're really too much for[n]me sometimes...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 23 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]I... need to go to the bathroom[n]for a second.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]When should I give him the gift?[n][f 1 3 65535][w][e]

[msg MND_011_0_0]
[s][vp 8 0 0 0 65535 0]○○○ is calling me...[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]I can't answer this now...![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Sorry, dude. Didn't mean to[n]take that long.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Shouldn't ya answer that call ya got?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's not a big deal.[e]
[s]Don't worry about it.[e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Oh... Okay, then.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Hey, dude. Sorry for takin' so long.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Announcer]]
[s][vp 8 0 0 0 65535 0]Ladies and gentlemen, thank you for[n]joining us on this special day.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We wish you all an unforgettable[n]evening, with one last finishing touch[n]from us...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7183 65535 0]Huh? What's goin' on?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 2 0 7040 65535 0]Whoa...[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]I have a gift for you.[e]
[s]I want you to have this.[e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7039 65535 0]Huh? For real!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You really... Thank you, man...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 20 4 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7115 65535 0]Is this really happenin'? This whole[n]day has been some sorta dream...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]First the aquarium, then this...[n]You've been surprisin' me all day.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]It's all real.[e]
[s]You're wide awake.[e]
[s]It's all for you.[e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]It really doesn't feel like it.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]I really hope so.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 24 4 0][f 4 10 65535 0 0][vp 8 2 0 7041 65535 0]Y-You're killin' me with all[n]this, man! How the hell did ya[n]think of all this!?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 21 4 0][f 4 10 65535 0 0][vp 8 2 0 7173 65535 0]You've been spoilin' me this entire[n]day. I don't even know how to react.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You're a serious natural at this.[n]I can't keep up.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7028 65535 0]Ever since we've been... together,[n]you've been surprisin' me left and right.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You... make me glad that I chose[n]to be with ya before.[n][f 1 3 65535][w][e]
[s][bup 0 2 21 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'm lucky to have ya with me.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Thanks.[e]
[s]You're making me blush.[e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 2 0 7071 65535 0]We have a lotta time left, ya know.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You've been surprisin' me all day.[n]I'm sure ya have more to show, yeah?[n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Ryuji and I spent some[n]time alone together...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Once it got late, I walked him[n]back to the station...[n][f 1 3 65535][w][e]

