[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]You... reserved this!?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]I did.[e]
[s]It was recommended to me.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0]To think you could get a[n]place like this...![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]And that I would get to[n]eat at a place like this.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4188 65535 0]Who would you know to get[n]a place like this for us?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It probably costs a fortune[n]just to reserve spots.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]The selection is superb as well.[n]They even have traditional items.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do not know where to even[n]start in deciding.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]We have time.[e]
[s]Get whatever you want.[e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am certain it would be expensive to[n]get anything I wanted, though.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4031 65535 0]You are truly astonding, [fName].[n][f 1 3 65535][w][e]
[s][bup 0 5 21 65535 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You are the only person to ever cause[n]me to be speechless. A brilliant light[n]illuminating the heart.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 23 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You make me... Well...[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]What is it?[e]
[s]Make you what?[e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 23 65535 0][f 4 10 65535 0 0][vp 8 2 0 4027 65535 0]I apologize. I need to step[n]out for a moment.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]When should I give him the gift?[n][f 1 3 65535][w][e]

[msg MND_011_0_0]
[s][vp 8 0 0 0 65535 0]○○○ is calling me...[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]I can't answer this now...![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]I apologize for the wait.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Were you not getting a call?[n]Should you not answer?[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's not a big deal.[e]
[s]Don't worry about it.[e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]Oh... I see.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]Apologies for keeping you waiting.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Announcer]]
[s][vp 8 0 0 0 65535 0]Ladies and gentlemen, thank you for[n]joining us on this special day.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We wish you all an unforgettable[n]evening, with one last finishing touch[n]from us...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4188 65535 0]Hm? What is this?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]Remarkable...[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]I have a gift for you.[e]
[s]I want you to have this.[e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]These are... for me...?[n][f 1 3 65535][w][e]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0]They are stunning. Thank you...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 21 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]I never thought that something so[n]bewilderindly poetic and lovely would[n]happen to me on this way.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It does not feel real. It feels as[n]if I am in a beautiful dream, or an[n]alluringly painted canvas.[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]It's all real.[e]
[s]You're wide awake.[e]
[s]The alluring one is in front of me.[e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]I certainly hope so.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I almost want to be here, with you, forever.[n]It's art in and of itself...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]I almost want to ask you to[n]pinch me to figure that out myself.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][bup 0 5 24 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 2 0 4047 65535 0]To think you would have such[n]a way with words. Did you always have[n]such... beguiling lines?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0]This day... has been perfect, [fName].[n]If it was an art piece, it would[n]be the most astonishing one I've seen.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You did so much for me. I never[n]thought I would get this sort of thing[n]for myself in the past.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I thought of it to just be something[n]only seen in the art people share.[n]Never truly obtainable.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]I do suppose you have always[n]been this way, however.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You work for the sake of others.[n]Even in despair, you work to[n]make others happy.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is truly admirable...[n]It is what I am drawn to.[n]What everyone is drawn to.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Thanks.[e]
[s]You're making me blush.[e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 20 65535 0][f 4 10 65535 0 0][vp 8 2 0 4127 65535 0]You know... the night isn't over just yet.[n][f 1 3 65535][w][e]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We have plenty of time to be alone,[n]if you so desire...[n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke and I spent some[n]time alone together...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Once it got late, I walked him[n]back to the station...[n][f 1 3 65535][w][e]

