[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Can I come over tomorrow night?[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]We haven't seen each other[n]in a while...[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]I really want to see you![n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Tomorrow works.[e]

[msg MSG_020_0_0 [Mishima]]
[s][f 5 14]Really!? Okay![n][w][e]

[msg MSG_021_0_0 [Mishima]]
[s][f 5 14]I'll come over tomorrow![n][f 5 15][w][e]

