[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]I was unable to ask you[n]in person due to the[n]others being there.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]I have a strong desire[n]to see you.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Are you free tomorrow?[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I'm free.[e]

[msg MSG_020_0_0 [Yusuke]]
[s][f 5 14]Then it's settled. I will[n]come over tomorrow night.[n][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][f 5 14]I look forward to seeing you.[n][f 5 15][w][e]

