[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hey, dude![n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Was wonderin' if ya[n]wanted to hang a bit?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]We haven't been able[n]to as of late, so[n]I wanted to reach out.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's hang out.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Nice! I'll meet up[n]with ya, then![n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14]I'll meet ya at the gym.[n][n][w][e]

