[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hey, dude. We couldn't speak[n]much before.[n][w][e]

[msg MSG_000_5_0 [Ryuji]]
[s][f 5 14]Could I come over tomorrow?[n][w][e]

[msg MSG_000_7_0 [Ryuji]]
[s][f 5 14]I kinda wanna talk to you.[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]You can come over.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Thanks, bro.[n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14]See ya then![n][w][e]

