[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]I have some free time to myself[n]and was planning on going to[n]the beach to relax my mind.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]While traveling over that way...[n]my mind ending up wondering to you.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Would you be interested in spending[n]some time together at the beach?[n]Just the two of us.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I'll meet you there.[e]

[msg MSG_020_0_0 [Yusuke]]
[s][f 5 14]It is set, then. We shall enjoy the[n]beautiful sights of Hawaii together![n][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][f 5 14]Perhaps they will have something there[n]to eat as well.[n][f 5 15][w][e]

