[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hey, dude.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Sorta wanna hang after[n]everything earlier.[n][f 5 15][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]You down?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's hang.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Nice! All right![n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14]I'll meet up with ya[n]in Shibyua.[n][f 5 15][w][e]

