[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]This may be rather sudden[n]given what had just occurred[n]not even hours ago...[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]However, I would not miss this[n]chance to capture the romance[n]of spending Christmas with a "lover"![n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]This experience would surely give[n]plenty of inspiration for my art...[n][f 5 15][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]And allow our hearts to become closer as well.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's get that inspiration.[e]

[msg MSG_020_0_0 [Yusuke]]
[s][f 5 14]Fantastic! It is settled.[n][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][f 5 14]I shall wait for you at[n]the Shibuya station.[n][f 5 15][w][e]

