[msg MSG_000_0_0 [Akechi]]
[s][f 5 14]I have time.[n][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][f 5 14]I said I would play along[n]with you before.[n][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][f 5 14]Are you coming or not?[n][w][e]

[msg MSG_REACTION [Akechi]]
[s][f 5 14]I will be at the usual spot.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]What's the plan? Are you gonna go see[n]Akechi?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Go see him[e]
[s]Cancel[e]

[sel SEL_002 top]
[s][f 5 14]I'm coming.[e]

