[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]It's Christmas Eve![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]I was thinking of you[n]for a bit![n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]So... do you want to meet up!?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Sure.[e]

[msg MSG_020_0_0 [Mishima]]
[s][f 5 14]Really!? Okay![n][w][e]

[msg MSG_021_0_0 [Mishima]]
[s][f 5 14]I'll be at the Shibuya Station![n][f 5 15][w][e]

