[msg MSG_000_0_0 [Mishima]]
[s][f 5 14][fName]![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]It's Christmas Eve![n][f 5 15][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Can we maybe see each other?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's meet up.[e]

[msg MSG_020_0_0 [Mishima]]
[s][f 5 14]R-Really!? Okay![n][w][e]

[msg MSG_021_0_0 [Mishima]]
[s][f 5 14]I'll be in Shibuya![n][f 5 15][w][e]

