[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Hey, dude. So... um...[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]I was wonderin' if ya wanted[n]to... you know... spend some[n]time together.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]I'm here with Mishima and all...[n]But I wanted to be with[n]you alone.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]I'll meet with you.[e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]For real? Nice![n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14]Then... I'll meet with ya[n]at the beach, OK?[n][f 5 15][w][e]

