[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]H-Hey! [fName]![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]D-Do you want to maybe[n]take a walk together?[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]I was thinking on you for[n]a while now and wanted[n]to be with you![n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's take a walk.[e]

[msg MSG_020_0_0 [Mishima]]
[s][f 5 14]Re-really!?[n][w][e]

[msg MSG_021_0_0 [Mishima]]
[s][f 5 14]I'll be at the beach, then![n][f 5 15][w][e]

