[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Greetings, [fName].[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]I heard some students talking[n]about some post-festival party[n]happening soon.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]As it so happens, I have yet[n]to leave your school's grounds.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Let's spend it together.[e]

[msg MSG_020_0_0 [Yusuke]]
[s][f 5 14]So you were thinking the same.[n][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][f 5 14]I quite enjoy the thought of[n]spending a festival with you...[n][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][f 5 14]Well then, let us meet up.[n][f 5 15][w][e]

