[sel SEL_C04_SPOT_00_02 top]
[s]Let's go somewhere fun.[e]
[s]Let's go to my room.[e]
[s]Let's do some people watching.[e]

[msg MSG_C04_MYROOM_00_00 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][f 4 23 1 304 3 10 0 10]......[n][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 304 3 10 0 10]Then it is decided.[n]Let us head off.[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]I have a special band[n]with Yusuke...[n][w][e]

[msg MSG_C04_YES_09_01 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]You see, I have entered my new piece[n]into Kawanabe's competition.[n][w][e]
[s][f 4 10 65535 0 0]Gratefully, it was accepted, and the exhibition[n]is being held at the same museum as last time.[n][w][e]
[s][f 4 10 65535 0 0]I was anticipating seeing the results.. together.[n]Perhaps.. we could do something afterwards.[n][w][e]
[s][f 4 10 65535 0 0]Come, let us go.[n][w][e]

[msg MSG_C04_YES_10_01 [Yusuke]]
[s][bup 0 5 4 65535 1][f 4 20 65535 0 0][f 4 23 1 204 3 10 0 10]Very well, then. Let us go.[n][w][e]

[sel SEL_C04_SPOT_00_02_2 top]
[s]Let's go somewhere fun.[e]
[s]Let's go to my room.[e]
[s]Let's do some people watching.[e]

[msg MSG_C04_MYROOM_00_00_2 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][f 4 23 1 304 3 10 0 10]......[n][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 304 3 10 0 10]Then it is decided.[n]Let us head off.[n][w][e]