[msg MSG_C08_BEGIN_D08_00_00 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]Good timing. I was meaning to speak to you.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]We need to talk more on the[n]current situation at hand.[n][w][e]

[msg MSG_C08_BEGIN_D08_00_01 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]Don't we have something better to do[n]than just hanging out?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 208 3 10 0 10]Your time would be much better spent[n]on combat contingencies instead of[n]idle chitchat.[n][w][e]

[msg MSG_C08_BEGIN_D08_00_02 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]What, you came just to see me? Just[n]the sort of brainless sentimentality[n]I'd expect from you.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]All we can do is wait until the date[n]Maruki gave us. Use that time to make[n]your preparations. Understood?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 208 3 10 0 10]If we're going to do this, we need to hit[n]him with everything we've got. I suggest[n]you make sure you're capable of that.[n][w][e]

[msg MSG_AKECHI_COOP_C08_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It would be best to speak[n]now to get our thoughts intact.[n][w][e]

[msg MSG_AKECHI_COOP_C09_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Are you coming or not?[n]It is best not to waste time.[n][w][e]

[msg MSG_C08_YES_08_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You want to speak with me?[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]This better be important.[n]We have serious matters to get to.[n][w][e]

[msg MSG_C08_YES_09_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]I wish to speak to you[n]about what we discussed before.[n][w][e]
[s][f 4 10 65535 0 0]Follow me.[n][w][e]

[msg MSG_C08_YES_09_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]Follow me.[n][w][e]

[msg MSG_C08_REV_FIGHT_00_01 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We have something to discuss, don't we?[n][w][e]

[sel SEL_COOP_REV_FIGHT top]
[s]We do.[e]
[s]We need to focus on Maruki.[e]

[msg MSG_C08_REV_FIGHT_00_02 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Then let's go. No need to waste time.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I am sure you can keep up.[n][w][e]

[msg MSG_C08_REV_FIGHT_00_03 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Make sure you prepare correctly.[n]The thieves don't need their leader to[n]get distracted, do they?[n][w][e]

[msg MSG_C08_REV_SPOT_00_00 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]What? You want to spend[n]time together?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]So sentimental. Fine.[n]What do you want to do?[n][w][e]

[sel SEL_C08_REV_SPOT_00_01 top]
[s]Let's go to my room.[e]
[s]Let's go on a date.[e]
[s]Let's go somewhere quiet.[e]

[msg MSG_C08_MYROOM_00_10_LVR [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]What? Are you being serious?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Do you not have anything better[n]to do but invite me over?[n][w][e]
[s]......[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Fine. You seem to be too stuck[n]on this topic to even try debating.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Let's go.[n][w][e]

[msg MSG_C08_REV_SPOT_00_10 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Fine, then. Where do you want[n]to go, exactly?[n][w][e]