[msg MND_COOP_RANK_MAX_01]
[s]I have a special bond[n]with Ryuji...[n][w][e]

[msg MSG_C07_YES_09_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7060 65535 0]Okay... Let's grab some ramem.[n][w][e]
[s][f 4 10 65535 0 0]We can talk at your place after...[n]About before.[n][w][e]

[sel SEL_C07_SPOT_00_02 top]
[s]Let's go somewhere fun.[e]
[s]Let's go to my room.[e]
[s]Let's train.[e]

[msg MSG_C07_MYROOM_00_00 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Your room...?[n][w][e]
[s][bup 0 2 6 65535 0][f 4 10 65535 0 0]O-okay... That works. Let's go...![n][w][e]

[msg MSG_C07_YES_10_01 [Ryuji]]
[s][bup 0 2 6 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Okay! I've been wantin' to[n]be with you a bit more.[n][w][e]
[s][f 4 10 65535 0]Let's go![n][w][e]

[msg MSG_RYUJI_CORP_C09_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 0 65535 0]Hey, man.[n][w][e]
[s][f 4 10 65535 0 0]I was thinkin' about gettin' some ramen and,[n]ya know, talkin' about everything.[n][w][e]
[s][f 4 10 65535 0 0]Ya comin' with...? We sorta need to talk...[n][w][e]