[msg GENERIC_HELP_00]
[s]Should I take Akechi[n]to the museum...?[n][e]

[msg GENERIC_HELP_01]
[s]Should I take Akechi[n]to the planetarium...?[n][e]

[msg GENERIC_HELP_02]
[s]Should I take Akechi[n]to Sky Tower...?[n][e]

[msg GENERIC_HELP_03]
[s]Should I take Akechi[n]to the aquarium...?[n][e]

[msg GENERIC_HELP_04]
[s]Should I take Akechi[n]to eat monjayaki...?[n][e]

[msg GENERIC_HELP_05]
[s]Should I take Akechi[n]to Destinyland...?[n][e]

[msg GENERIC_HELP_06]
[s]Should I take Akechi[n]to Dome Town...?[n][e]

[msg GENERIC_HELP_07]
[s]Should I take Akechi[n]to ride the Ferris wheel...?[n][e]

[msg GENERIC_HELP_08]
[s]Should I take Akechi[n]to Book Town...?[n][e]

[msg GENERIC_HELP_09]
[s]Should I take Akechi[n]to Meiji Shrine...?[n][e]

[msg GENERIC_HELP_10]
[s]Maybe we shouldn't go[n]anywhere right now...[n][e]

[msg MSG_C08_BEGIN_D08_00_00 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]Good timing. I was meaning to speak to you.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]We need to talk more on the[n]current situation at hand.[n][w][e]

[msg MSG_C08_BEGIN_D08_00_01 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]Don't we have something better to do[n]than just hanging out?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 208 3 10 0 10]Your time would be much better spent[n]on combat contingencies instead of[n]idle chitchat.[n][w][e]

[msg MSG_C08_BEGIN_D08_00_02 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0][f 4 23 1 208 3 10 0 10]What, you came just to see me? Just[n]the sort of brainless sentimentality[n]I'd expect from you.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]All we can do is wait until the date[n]Maruki gave us. Use that time to make[n]your preparations. Understood?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 208 3 10 0 10]If we're going to do this, we need to hit[n]him with everything we've got. I suggest[n]you make sure you're capable of that.[n][w][e]

[msg MSG_AKECHI_COOP_C08_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]It would be best to speak[n]now to get our thoughts intact.[n][w][e]

[msg MSG_AKECHI_COOP_C09_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Are you coming or not?[n]It is best not to waste time.[n][w][e]

[msg MSG_C08_YES_08_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]You want to speak with me?[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]This better be important.[n]We have serious matters to get to.[n][w][e]

[msg MSG_C08_YES_09_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]I wish to speak to you[n]about what we discussed before.[n][w][e]
[s][f 4 10 65535 0 0]Follow me.[n][w][e]

[msg MSG_C08_YES_09_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0]Follow me.[n][w][e]

[msg MSG_C08_REV_FIGHT_00_01 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We have something to discuss, don't we?[n][w][e]

[sel SEL_COOP_REV_FIGHT top]
[s]We do.[e]
[s]We need to focus on Maruki.[e]

[msg MSG_C08_REV_FIGHT_00_02 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Then let's go. No need to waste time.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]I am sure you can keep up.[n][w][e]

[msg MSG_C08_REV_FIGHT_00_03 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Make sure you prepare correctly.[n]The thieves don't need their leader to[n]get distracted, do they?[n][w][e]

[msg MSG_C08_REV_SPOT_00_00 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]What? You want to spend[n]time together?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]So sentimental. Fine.[n]What do you want to do?[n][w][e]

[sel SEL_C08_REV_SPOT_00_01 top]
[s]Let's go to my room.[e]
[s]Let's go on a date.[e]
[s]Let's go somewhere quiet.[e]

[msg MSG_C08_MYROOM_00_10_LVR [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]What? Are you being serious?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Do you not have anything better[n]to do but invite me over?[n][w][e]
[s]......[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Fine. You seem to be too stuck[n]on this topic to even try debating.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Let's go.[n][w][e]

[msg MSG_C08_REV_SPOT_00_10 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Fine, then. Where do you want[n]to go, exactly?[n][w][e]

[sel SEL_C08_REV_SPOT_00_10 top]
[s]Go to Ueno[ref 0 0][e]
[s]Go to Ikebukuro[ref 1 1][e]
[s]Go to Asakusa[ref 2 2][e]
[s]Go to Sinagawa[ref 3 3][e]
[s]Go to Tsukishima[ref 4 4][e]
[s]Go to Maihama[ref 5 5][e]
[s]Go to Suidobasi[ref 6 6][e]
[s]Go to Odaiba[ref 7 7][e]
[s]Go to Jinbocho[ref 8 8][e]
[s]Go to Meijijingu[ref 9 9][e]
[s]Don't go anywhere[ref 10 10][e]

[msg MSG_AKECHI_SPOT_UENO [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]The museum? A rather tame option[n]from you.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]I suppose we can go.[n]Let's head there now.[n][w][e]

[msg MSG_AKECHI_SPOT_UENO_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Last time was a rather[n]intriguing talk.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]I am fine with going again.[n]You can lead the way.[n][w][e]

[msg MSG_AKECHI_SPOT_IKEBUKUR [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]You want to go to the planetarium?[n]I have not went there before.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]This better not disappoint me, [fName].[n][w][e]

[msg MSG_AKECHI_SPOT_IKEBUKUR_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Last time did not disappoint.[n]A rather pleasant surprise.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Is there something new this time?[n]I suppose we shall find out.[n][w][e]

[msg MSG_AKECHI_SPOT_SKYTREE [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]That tower, right? Fine, I guess[n]that works.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Shall we get going?[n][w][e]

[msg MSG_AKECHI_SPOT_SKYTREE_ [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Again? I guess it isn't an issue.[n][w][e]

[msg MSG_AKECHI_SPOT_SHINAGAW [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, yes. The aquarium. I suppose[n]we could go there.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]How about we head there now?[n][w][e]

[msg MSG_AKECHI_SPOT_SHINAGAW_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]I do suppose going there again[n]would be fine. Let us go.[n][w][e]

[msg MSG_AKECHI_SPOT_TSUKISHI [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]You want to get some Monjayaki?[n]I suppose I have not eaten.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]Why don't we head off now?[n][w][e]

[msg MSG_AKECHI_SPOT_TSUKISHI_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54439 65535 0]Making it myself last time[n]worked out well. I will make[n]it again this time.[n][w][e]

[msg MSG_AKECHI_SPOT_MAIHAMA [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Why do you wish to go there?[n]I doesn't seem very helpful[n]in this moment...[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]But very well. Let us go now.[n][w][e]

[msg MSG_AKECHI_SPOT_MAIHAMA_ [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]It wasn't too offensive the first time.[n]I suppose I will go along.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Let's head over now.[n][w][e]

[msg MSG_AKECHI_SPOT_SUIDOBAS [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Dome Town? I will admit I am curious[n]what you are like on those rides.[n][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Fine then. Let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_SUIDOBAS_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]You want to go on more rides[n]again, correct? Then let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_ODAIBA [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]That's where the Ferris wheel is, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]I see... I can tell where[n]you're going with this. Fine.[n]Let's get going.[n][w][e]

[msg MSG_AKECHI_SPOT_ODAIBA_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]You want to go on the Ferris wheel[n]again, correct? Let's go then.[n][w][e]

[msg MSG_AKECHI_SPOT_JINBO [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Jinbocho? A surprising request.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]That is fine. Let us go now.[n][w][e]

[msg MSG_AKECHI_SPOT_JINBO_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Again? All right. I am fine[n]getting more books. Let us go.[n][w][e]

[msg MSG_AKECHI_SPOT_MEIJI [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]A shrine?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sounds simple enouugh. Let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_MEIJI_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0]It was peaceful last time we went.[n]I am fine going again.[n][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Lead the way.[n][w][e]

[msg MSG_AKECHI_SPOT_CANCEL [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Make up your mind already.[n][w][e]

[msg MSG_LOCATION_CHECK_3RD_R [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]You don't know where that is...[n][w][e]