[msg MND_COOP_RANK_MAX_01]
[s]I have a special bond[n]with Mishima...[n][w][e]

[msg MSG_C18_YES_09_01 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 23 1 218 3 10 0 10][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y-you see.. well...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 19051 65535 0]I kind of wanted to maybe go[n]somewhere with you... If that's fine[n]with you, of course![n][w][e]
[s][f 4 10 65535 0 0]L-Let's go![n][w][e]

