[msg MSG_AKECHI_SPOT_UENO [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]The museum? A rather tame option[n]from you.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]I suppose we can go.[n]Let's head there now.[n][w][e]

[msg MSG_AKECHI_SPOT_UENO_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Last time was a rather[n]intriguing talk.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]I am fine with going again.[n]You can lead the way.[n][w][e]

[msg MSG_AKECHI_SPOT_IKEBUKUR [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]You want to go to the planetarium?[n]I have not went there before.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]This better not disappoint me, [fName].[n][w][e]

[msg MSG_AKECHI_SPOT_IKEBUKUR_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Last time did not disappoint.[n]A rather pleasant surprise.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Is there something new this time?[n]I suppose we shall find out.[n][w][e]

[msg MSG_AKECHI_SPOT_SKYTREE [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]That tower, right? Fine, I guess[n]that works.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]Shall we get going?[n][w][e]

[msg MSG_AKECHI_SPOT_SKYTREE_ [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Again? I guess it isn't an issue.[n][w][e]

[msg MSG_AKECHI_SPOT_SHINAGAW [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, yes. The aquarium. I suppose[n]we could go there.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]How about we head there now?[n][w][e]

[msg MSG_AKECHI_SPOT_SHINAGAW_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]I do suppose going there again[n]would be fine. Let us go.[n][w][e]

[msg MSG_AKECHI_SPOT_TUKISHIM [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]You want to get some Monjayaki?[n]I suppose I have not eaten.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0]Why don't we head off now?[n][w][e]

[msg MSG_AKECHI_SPOT_TUKISHIM_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54439 65535 0]Making it myself last time[n]worked out well. I will make[n]it again this time.[n][w][e]

[msg MSG_AKECHI_SPOT_MAIHAMA [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Why do you wish to go there?[n]I doesn't seem very helpful[n]in this moment...[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]But very well. Let us go now.[n][w][e]

[msg MSG_AKECHI_SPOT_MAIHAMA_ [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]It wasn't too offensive the first time.[n]I suppose I will go along.[n][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Let's head over now.[n][w][e]

[msg MSG_AKECHI_SPOT_SUIDOBAS [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Dome Town? I will admit I am curious[n]what you are like on those rides.[n][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Fine then. Let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_SUIDOBAS_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]You want to go on more rides[n]again, correct? Then let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_ODAIBA [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]That's where the Ferris wheel is, right?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]I see... I can tell where[n]you're going with this. Fine.[n]Let's get going.[n][w][e]

[msg MSG_AKECHI_SPOT_ODAIBA_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]You want to go on the Ferris wheel[n]again, correct? Let's go then.[n][w][e]

[msg MSG_AKECHI_SPOT_JINBO [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Jinbocho? A surprising request.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]That is fine. Let us go now.[n][w][e]

[msg MSG_AKECHI_SPOT_JINBO_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Again? All right. I am fine[n]getting more books. Let us go.[n][w][e]

[msg MSG_AKECHI_SPOT_MEIJIJIN [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]A shrine?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sounds simple enouugh. Let's go.[n][w][e]

[msg MSG_AKECHI_SPOT_MEIJIJIN_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0]It was peaceful last time we went.[n]I am fine going again.[n][w][e]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Lead the way.[n][w][e]

[msg MSG_AKECHI_SPOT_CANCEL [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Make up your mind already.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_A_2 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]Why don't we go somewhere else?[n][w][e]

[msg MSG_RYUJI_SPOT_SUIDOUBAS_3 [Ryuji]]
[s][bup 0 2 20 65535 0][f 4 10 65535 0 0]Dome Town...? Is this for, like...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]...Well, okay. I've been wantin'[n]to go on some coasters![n][w][e]

[msg MSG_RYUJI_SPOT_AKIHABARA_3 [Ryuji]]
[s][bup 0 2 24 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]So, like... a date in Akihabara...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]U-Um... Sure. Let's go.[n][w][e]

[msg MSG_YUSUKE_SPOT_IKEBUKUR_3 [Yusuke]]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 204 3 10 0 10]A date to the planetarium?[n]A beautiful vision, indeed.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us go, [fName]! We must seize this idea.[n][w][e]

[msg MSG_YUSUKE_SPOT_MEIJIJIN_3 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]A shrine, hm? Experiencing traditional[n]culture with you may help my inspiration.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Let us go. I'll be counting[n]on you to lead the way.[n][w][e]