[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Making coffee.[clr 27][e]
[s]Having game.[e]
[s]No idea.[e]

[sel SEL_022_2_0 top]
[s][f 0 8 2 1 2217]I want the ladies to love me.[clr 27][e]
[s][f 0 8 2 1 2217]I want the guys to love me.[clr 27][e]
[s]I don't care about that stuff.[e]

[msg MSG_022_3_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0]Oh? I didn't realize you were...uh, never mind.[n][f 1 3 65535][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5048 65535 0][coop 6 5 1003]Long as you're paying attention, it's no[n]skin off my nose. Guys like a good barista[n]as much as ladies do, right?[n][f 1 3 65535][w][e]