[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]With this strength, I am not[n]worried that we will win against Maruki.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But this outcome does raise questions.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You have been with your persona[n]for less than a year, yet you are[n]able to defeat me twice.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Just how have you done this?[n]What do you have that I do not?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]I fight for my friends.[e]
[s]A long-nosed man...[e]
[s]I don't know.[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Such nonsense. I nearly forgot[n]about that needless sentimentality[n]of yours...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Are you messing with me?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 8161 65535 0]You don't know? Are you serious?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Either way, you have caught up[n]to me on every front. Perhaps[n]even surpassed me.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]A rather infuriating thought...[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]I couldn't lose.[e]
[s]You think I am stronger?[e]
[s]We should train together.[e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Heh... At least you are taking[n]this seriously.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]I can't do away with that thought.[n]Annoying... but a possibility.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]And why would we do that?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54404 65535 0]Even now, I still hate you.[n]Do not think that the recent[n]events means we are friends.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]The only thing keeping us[n]here is Maruki. That is all.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Now that you have won against[n]me at my true form, that feeling[n]is stronger than ever.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]I don't hate you.[e]
[s]You still hate losing, huh?[e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54417 65535 0]Well, that is too bad now, isn't[n]it? Doesn't change a single thing.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8043 65535 0]Yes. You seem to bring up quite[n]a lot of competitve nature in me.[n][f 1 3 65535][w][e]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Yet another thing which annoys me.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8051 65535 0]We should go. It is getting late.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Do you need your glove back?[e]
[s]What about the glove?[e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][vp 8 2 0 0 65535 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]Keep it. I do not need it.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Call me when we are going[n]into Maruki's palace.[n][f 1 3 65535][w][e]

