[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Greetings, [fName]. I am glad you have[n]decided to join me.[n][f 1 3 65535][w][e]

[msg MND_000_5_0]
[s][vp 8 0 0 0 65535 0]It seems like Yusuke has been[n]waiting for me here...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 2 0 4087 65535 0]Is something the matter?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You seem to be looking at something[n]quite intently.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]You really are a pretty guy...[clr 27][e]
[s]You're still in your jacket.[e]
[s][f 0 8 2 1 2217]The Waikiki beach.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 324 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I... appreciate the compliment.[n][f 1 3 65535][w][e]
[s][bup 0 5 321 0 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]I believe you to be rather[n]prepossessing as well.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]Indeed. I tend to sunburn rather easily.[n]Unfortunate, but nothing to fret over.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]The waters are rather beautiful.[n]I understand why you'd be[n]drawn to such a sight.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well then, shall we head off?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]There are many sights to see[n]which we cannot by staying here.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 4 300 1][vp 8 2 0 4040 65535 0]...Oh! Is that...![n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Yusuke]]
[s][bup 0 5 304 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Such an exquisite aroma![n]I believe this is a rather popular[n]Hawaiian delicacy![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][fName]! We must try it![n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s][f 0 8 2 1 2217]Good food is also part of travelling.[clr 27][e]
[s]Will it help with your art?[e]
[s]Am I paying?[e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 15 15 5]Precisely. We must be sure[n]to explore to the fullest.[n][n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Not... exactly. But[n]it's good food.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 304 0 0][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]Are you not?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]But I don't have any money...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Excuse me, sir. May we acquire two[n]servings of the Garlic Shrimp?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]Magnificent! Such large portions[n]as well.[n][f 1 3 65535][w][e]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I thank you for paying for[n]both of us.[n][f 1 3 65535][w][e]

[msg MND_014_5_0]
[s][vp 8 0 0 0 65535 0]We gazed out over the ocean[n]while we enjoyed the delicate[n]flavors of a foreign country...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Shrimp Stand Owner]]
[s]You two from Japan?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]That is correct.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Shrimp Stand Owner]]
[s]How 'bout them Phantom Thieves, huh?[n]The guys that steal hearts![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 304 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh? I did not think they[n]would be spoken of here as well.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Where did you acquire information[n]about... that group?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Shrimp Stand Owner]]
[s]Heard about it on the news![n]They're all the rage in Japan, yeah?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Even across the waters, we[n]seem to have some sort of influence.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Shrimp Stand Owner]]
[s]Say, if y'run into 'em, tell 'em I say hello.[n][f 1 3 65535][w][e]
[s]And ask 'em to change people's hearts[n]so everyone loves shrimp![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 302 0 0][f 4 10 65535 0 0][vp 8 2 0 4044 65535 0]Absurd! Never have I heard such[n]a negligible request![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 302 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Come on, [fName]. Let us go.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]We spent time on the beach until the[n]sun began to sink below the horizon...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A beautifully colored tapestry.[n]Hawaii's horizon is truly phenomenal.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]Today has been the definition of exemplary.[n][f 1 3 65535][w][e]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It has been wonderful spending[n]this evening with you.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][bup 0 5 303 0 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]To be totally honest, I was[n]concerned about how this...[n]relationship would be.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]After all, it is not exactly[n]a typical one.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I cannot help but wonder how[n]the others shall handle the news[n]if we were to tell them.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]It doesn't matter.[e]
[s]I'm sure it'll be okay.[e]
[s][f 0 8 2 1 2217]I don't care as long as we're together.[clr 27][e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 321 0 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0][coop 15 5 5]Even now, you are ever so[n]confident. I admire that about[n]you.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 321 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 15 5 5]Your encouragement is soothing.[n]You certainly know how to stay[n]calm in rough times.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 321 0 0][f 4 10 65535 0 0][vp 8 2 0 4061 65535 0][coop 15 15 5]...I thank you, [fName].[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We have gotten thus far.[n]We can handle any obsticles in[n]the way as one.[n][f 1 3 65535][w][e]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is a work in progress, but[n]all canvases look lackluster before[n]the complete image is revealed.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I want you to have this.[n][f 1 3 65535][w][e]

[msg MND_034_1_0]
[s]It's a small, painted tiki mask.[n][f 1 3 65535][w][e]
[s]Something about the colorful, eccentric flare[n]of the paint job reminds me of Yusuke.[n][f 1 3 65535][w][e]

[msg MSG_034_3_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]I could not get much, unfortunately.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, I was able to paint it[n]to give it some extra class worthy[n]of the image it represents.[n][f 1 3 65535][w][e]

[sel SEL_034_5_0 top]
[s]Thank you.[e]
[s][f 0 8 2 1 2217]The paint is rather eccentric.[clr 27][e]

[msg MSG_034_7_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 15 10 5]It is nothing. Merely a small[n]souvenier to symbolize our[n]time together.[n][f 1 3 65535][w][e]

[msg MSG_034_9_0 [Yusuke]]
[s][bup 0 5 301 0 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 15 15 5]Yes. I believe it fits the[n]cultural background soundly.[n]It was too bland before.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][bup 0 5 300 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It seems that perhaps we are[n]running out of daylight.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We do not wish to be late[n]in heading back to our places[n]for the night.[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]I don't want you to go.[e]
[s]We have time.[e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 321 0 0][f 4 10 65535 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]I suppose a tad bit longer[n]would not harm us.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]The two of us basked in the[n]stunning Hawaiian sunset.[n]Just me and Yusuke...[n][f 1 3 65535][w][e]

