[msg MND_000_0_1]
[s][vp 8 0 0 0 65535 0]Yusuke and I roamed the[n]snowy Shibuya streets[n]for quite some time...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]The streets of Shibuya sure are[n]crowded during this time.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It seems we were not the only[n]ones with the idea of enjoying[n]time together during Christmas.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]All the couples happily enjoying[n]the holidays, as well as the snow which[n]is reflecting the lights of the streets.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]It is a gorgeous sight.[n]They would all make for a perfect[n]painting.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Do you envy them?[e]
[s]Wanting to paint couples again?[e]
[s][f 0 8 2 1 2217]You're all I was looking at.[clr 27][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 2 0 4044 65535 0][coop 15 10 5]What need would there be[n]to envy them?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]I have you, do I not?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][coop 15 5 5]Do not worry. This is not[n]the same as the times prior.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]If anything, it would be you[n]who I would wish to paint.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 24 4 0][coop 15 15 5]......[n][f 1 3 65535][w][e]
[s][bup 0 5 21 4 0][f 4 24 0 4 6 42 4 100][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]Ever the charmer, I see, [fName].[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nevertheless, [fName], what should we do?[n]It has been quite a while since[n]we had some time to ourselves.[n][f 1 3 65535][w][e]

[sel SEL_005_1_0 top]
[s][f 0 8 2 1 2217]Let's just relax.[clr 27][e]
[s][f 0 8 2 1 2217]Let's have some fun.[clr 27][e]
[s]Merry Christmas.[e]

[msg MSG_005_3_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][coop 15 15 5]That would be nice. We have not[n]had a chance to breathe for days now.[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4149 65535 0][coop 15 15 5]My apologies, however I do not know[n]what would be considered "fun"[n]in this moment.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I spend my time painting and diving[n]into artistic literature.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Unfortunately, that is not something[n]others find intriguing.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0][coop 15 10 5]I supposed we had not had[n]the chance to say this to each[n]other just yet. Merry Christmas, [fName].[n][f 1 3 65535][w][e]

[msg MND_011_5_0]
[s][vp 8 0 0 0 65535 0]I won't be able to see Yusuke[n]again after tomorrow...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We spent a long time talking...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Before I forget, I have something to hand you.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4030 65535 0]A gift from me.[n]I wanted to thank you... for everything.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Thank you.[clr 27][e]
[s][f 0 8 2 1 2217]I'll cherish it.[clr 27][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0][coop 15 15 5]I am relieved you enjoy it.[n]I was worried it was too avant[n]garde for your tastes.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 2 4 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am sorry if this brings[n]the mood down. However, this has[n]been on my mind for quite a while.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you... truly okay?[n]The way you were handled while[n]in custody was truly atrocious.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It would not be abnormal for you[n]to have some scarring due to that[n]experience. Physically... and emotionally.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]I just want to be completely[n]positive you are well.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I wanted to bring this up earlier,[n]but I couldn't with the past situation.[n]It all happened too suddenly.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If something is bothering you,[n]you know I am here to ease your worries;[n]right, [fName]?[n][f 1 3 65535][w][e]

[msg MSG_999_0_0 [Sae]]
[s]If that happens, there's no telling what[n]they'll do to you or your teammates.[n][f 1 3 65535][w][e]
[s]There's even the possibility that they'll[n]fabricate a crime and move to arrest[n]you all.[n][f 1 3 65535][w][e]

[msg MND_999_1_0]
[s][vp 1 0 0 0 0 0]I have to turn myself in to[n]make sure Yusuke stays safe...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]But telling him about it would[n]only cause him to panic...[n][f 1 3 65535][w][e]

[msg MSG_013_1_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][fName], please, tell me what is[n]troubling you.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]It's nothing.[e]
[s]I'm sorry.[e]

[msg MSG_014_1_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0]...I see.[n][f 1 3 65535][w][e]

[msg MSG_014_3_0 [Yusuke]]
[s][cut 1 65535 65535 65535 65535 65535 65535 65535 5 3 300 1][vp 8 2 0 4074 65535 0]......[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0]So even now you cannot tell[n]me your woes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It feels rather unfair, [fName]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Not for me... but for you.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I apologize for the sudden[n]departure, though it is getting[n]late, is it not?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]I'll walk you back.[e]
[s]Be careful.[e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4197 65535 0]No need. I will go myself.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4044 65535 0]It is not me who should be worried about.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]I must say, [fName], you are[n]not very good at keeping[n]secrets from me.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The expression you hold is of someone[n]who knows what they are about to[n]do, even if martyring themselves.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I held that expression once...[n]You know those results.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4063 65535 0]...Farewell.[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]I made Yusuke worry...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Even so, this is the only way...[n][f 1 3 65535][w][e]

