[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0]To think that everything[n]has been taken.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Even the more niche areas[n]are packed with evening goers...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]We can still enjoy ourselves.[e]
[s]It was last second, after all.[e]
[s]I'm fine if I'm with you.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0]That is true, though the bonus[n]of food would have been nice.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 4 0][f 4 24 0 4 6 35 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If I recall, people will also[n]get sweets on this day as well,[n]correct?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]You are correct. Last second spots on[n]Christmas Eve would be rather difficult[n]to obtain.[n][f 1 3 65535][w][e]
[s][bup 0 5 2 4 0][f 4 24 0 4 6 35 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, we shall not give up![n]We shall prevail in the end![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 21 4 0][f 4 10 65535 0 0][vp 8 2 0 4189 65535 0]You truly do have a way[n]with words, [fName].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It certainly isn't unwelcome.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 4 0][f 4 24 0 4 6 35 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, for as enticing as your[n]words are, it would be nice to get[n]something before we left.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I believe I saw a cake shop on[n]the way here. Let us stop by there.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 2 0 4074 65535 0]It does not seem like this[n]idea will bear any fruit either.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is worth a try, however.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Miss, would there happen to be[n]any cakes left?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Cheerful Female Employee]]
[s][vp 8 0 0 0 65535 0]Actually, we do![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 4 4 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]You do!? Sincerely?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Cheerful Female Employee]]
[s][vp 8 0 0 0 65535 0]One of our orders was canceled last-[n]minute. This is the only cake we have![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0]Remarkable...![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We shall take it.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Cheerful Female Employee]]
[s][vp 8 0 0 0 65535 0]Of course! Just wait one moment[n]while I go prepare your order![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]It seems we got a favorable[n]end after all.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 4 0][f 4 24 0 4 6 35 3 100][vp 8 0 0 0 65535 0]This only happens around you, [fName].[n]Do you have some sort of luck powers[n]as well?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Perhaps it's good karma.[e]
[s]It's because of our efforts.[e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]Indeed.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do believe our efforts[n]could cause positive outcomes[n]like this.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You especially deserve it.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 4 0][f 4 24 0 4 6 35 3 100][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]At any rate, let us go back to[n]your room once we get our order.[n][f 1 3 65535][w][e]

