[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is looking at all[n]the different types of books...[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is looking at all[n]the different types of books...[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][coop 5 10 5][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Goodbye.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Dummy e814_072[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Akechi is contemplating his[n]next book.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He appears to be enjoying his[n]newfound time to read.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with Akechi[n]will grow stronger soon...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Having this time is rather[n]peaceful, indeed. Let us go.[n][f 1 3 65535][w][e]

