[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4150 65535 0]In some religions, there are[n]specific gods for things such[n]as love and romance.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Praying to them is meant to bring[n]good fortune and prosperity in romance.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Would you ever wish to such gods?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Not really...[e]
[s]I'd like to try.[e]
[s][f 0 8 2 1 2217]I don't need to with you.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4026 65535 0][coop 5 5 5]I see. Do you not feel the need?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I suppose such things[n]are not proven anyway.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][coop 5 10 5]What would you do if you do[n]not get the match you wanted?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am rather curious myself.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0][coop 5 10 5]O-Oh...![n][f 1 3 65535][w][e]
[s][bup 0 5 21 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I-I do suppose it isn't...[n]exactly needed in this scenario...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Still, it is an intriquing topic.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Art has surrounded different cultures[n]and religions for millenia. Of course,[n]I studied it extensively.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]The reliance on a god to give[n]you a match, to give you romance...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is a strange concept. One I[n]must delve into and understand.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That reminds me, [fName]...[n]Even a one-yen offering is said[n]to bring divine favors, yes?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perhaps to know more on this,[n]one must do it themselves to see.[n][f 1 3 65535][w][e]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, I do not have much money...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4079 65535 0]You can have this, [fName].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It is all I could afford.[n]I want you to have it.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][vp 8 2 0 4049 65535 0]Let us walk to the station together.[n][f 1 3 65535][w][e]

