[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]So what ride are you planning[n]on going onto?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I am quite confident I can[n]keep up, so do not worry[n]about that.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Have you been here before?[e]
[s]What types do you like?[e]
[s]The Ferris wheel.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Once or twice, yes. Mostly[n]for publicity reasons.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Act like a normal high schooler[n]to show my "normal" side as well.[n]It was all worthless anyway.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]You're asking me? Well, let me see...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]I did enjoy the dropper rides.[n]However, the roller coasters were[n]entertaining as well.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54412 65535 0]Oh? Did you want to go on some[n]romantic ride with me?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, that is not what we[n]are here for.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Well, what are we waiting for?[n]I will show you just how[n]resilient I am.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54420 65535 0]You handle yourself quite well.[n]Rather fitting for you.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Though it seems I an the victor[n]this time around.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]It was a good battle.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]With this win, I say we should[n]head off.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]You seem like you need a rest.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][vp 8 2 0 8072 65535 0]Let us head home for now.[n][f 1 3 65535][w][e]

