[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]So this is why you wished[n]to come here...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I do supposed Ferris wheels are a[n]typical dating spot to go to.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]It is not surprising thinking[n]of it in that sense.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Is the analyzing necessary?[e]
[s]Do you like it?[e]
[s]It felt appropriate.[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]I need to figure out the proper[n]course of action, so it is indeed.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]It is a rather... pretty view[n]as others would call it.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]However, I am not one to enjoy[n]these types of sights.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I will have to disappoint you there.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54450 65535 0]Due to me humoring your[n]attempts, correct?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I suppose it is, yes. I will[n]continue to go along with it.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I have never actually been on[n]one of these before.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]I have always heard of people[n]loving the view and the ride with[n]their girlfriends.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Something about how "romantic"[n]this ride usually is.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Honestly? It seems rather dull.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]If we were to do anything,[n]I would prefer it to be a fight.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Perhaps we should do that[n]instead of this.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][vp 8 2 0 8072 65535 0]It is late. Let us head home for now.[n][f 1 3 65535][w][e]

