[msg GENERIC_HELP_10]
[s]Should I spend time[n]alone with Yusuke...?[n][e]

[msg GENERIC_HELP_11]
[s]Should I spend time[n]alone with Ryuji...?[n][e]

[msg GENERIC_HELP_12]
[s]Should I spend time[n]alone with Mishima...?[n][e]

[sel SEL_E65510400_TEL_001_00 top]
[s]Spend time with Ohya[ref 0 0][e]
[s]Spend time with Takemi[ref 1 1][e]
[s]Spend time with Kawakami[ref 2 2][e]
[s]Spend time with Hifumi[ref 3 3][e]
[s]Spend time with Chihaya[ref 4 4][e]
[s]Spend time with Futaba[ref 5 5][e]
[s]Spend time with Ann[ref 6 6][e]
[s]Spend time with Makoto[ref 7 7][e]
[s]Spend time with Haru[ref 8 8][e]
[s]Spend time with Sumire[ref 9 9][e]
[s]Spend time with Yusuke[ref 10 10][e]
[s]Spend time with Ryuji[ref 11 202][e]
[s]Spend time with Mishima[ref 12 203][e]

[msg MSG_E65510400_TEL_002_10 [Yusuke]]
[s][bup 0 5 0 4 1][f 4 10 65535 0 0][vp 8 2 0 4188 65535 0][fName]? It is quite the rarity for you to[n]be the one calling someone else.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 4 1][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]What is it that you need?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_11 [Ryuji]]
[s][bup 0 2 0 4 1][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Hey, dude. What's up?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_12 [Mishima]]
[s][bup 0 111 1 4 1][f 4 10 65535 0 0][vp 8 2 0 19067 65535 0][fName]! What's going on?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_10 [Yusuke]]
[s][bup 0 5 4 4 1][f 4 10 65535 0 0][vp 8 2 0 4040 65535 0]Shinagawa? Right this moment?[n][f 1 3 65535][w][e]
[s]......[n][f 1 3 65535][w][e]
[s][bup 0 5 1 4 1][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Very well. I will head your way, [fName].[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_11 [Ryuji]]
[s][bup 0 2 4 4 1][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0]Huh? Shinagawa?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 4 1][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I guess I can come, yeah.[n]See ya there![n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_12 [Mishima]]
[s][bup 0 111 1 4 1][f 4 10 65535 0 0][vp 8 2 0 19035 65535 0]Shinagawa? Sure! I'll go over now![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll see you there![n][f 1 3 65535][w][e]